// 专升本高频词汇 — 词根词缀法
// { word, phonetic, meaning, pos, root, rootMeaning, analysis, example, exampleCn, verbForms? }

const vocabularyData = [

  // ==================== spect/spic = 看 ====================
  { word: "aspect", phonetic: "/ˈæspekt/", meaning: "方面；外观", pos: "n", root: "spect", rootMeaning: "看", analysis: "a-(朝) + spect(看) → 看的角度 → 方面", example: "We must consider every aspect of the problem.", exampleCn: "我们必须考虑问题的各个方面。" },
  { word: "inspect", phonetic: "/ɪnˈspekt/", meaning: "检查；视察", pos: "v", root: "spect", rootMeaning: "看", analysis: "in-(向内) + spect(看) → 往里看 → 检查", example: "The officer came to inspect the factory.", exampleCn: "官员来视察工厂。" },
  { word: "respect", phonetic: "/rɪˈspekt/", meaning: "尊重；尊敬", pos: "v/n", root: "spect", rootMeaning: "看", analysis: "re-(再) + spect(看) → 一再注视 → 尊重", example: "You should respect your parents.", exampleCn: "你应该尊重父母。" },
  { word: "prospect", phonetic: "/ˈprɒspekt/", meaning: "前景；展望", pos: "n", root: "spect", rootMeaning: "看", analysis: "pro-(向前) + spect(看) → 向前看 → 前景", example: "The prospect of this project is bright.", exampleCn: "这个项目的前景是光明的。" },
  { word: "suspect", phonetic: "/səˈspekt/", meaning: "怀疑；嫌疑犯", pos: "v/n", root: "spect", rootMeaning: "看", analysis: "su-(下) + spect(看) → 向下看 → 怀疑", example: "I suspect he is lying.", exampleCn: "我怀疑他在撒谎。" },
  { word: "perspective", phonetic: "/pəˈspektɪv/", meaning: "观点；视角", pos: "n", root: "spect", rootMeaning: "看", analysis: "per-(贯穿) + spect(看) + -ive → 看透 → 视角", example: "Try to see it from my perspective.", exampleCn: "试着从我的角度看问题。" },

  // ==================== dict/dic = 说 ====================
  { word: "predict", phonetic: "/prɪˈdɪkt/", meaning: "预测；预言", pos: "v", root: "dict", rootMeaning: "说", analysis: "pre-(预先) + dict(说) → 预先说 → 预测", example: "It's hard to predict the weather.", exampleCn: "天气很难预测。" },
  { word: "indicate", phonetic: "/ˈɪndɪkeɪt/", meaning: "表明；指示", pos: "v", root: "dic", rootMeaning: "说", analysis: "in-(向) + dic(说) + -ate → 向…说 → 表明", example: "Research indicates that exercise improves health.", exampleCn: "研究表明锻炼有益健康。" },
  { word: "contradict", phonetic: "/ˌkɒntrəˈdɪkt/", meaning: "矛盾；反驳", pos: "v", root: "dict", rootMeaning: "说", analysis: "contra-(反对) + dict(说) → 反着说 → 矛盾", example: "His actions contradict his words.", exampleCn: "他的言行自相矛盾。" },
  { word: "dedicate", phonetic: "/ˈdedɪkeɪt/", meaning: "致力于；奉献", pos: "v", root: "dic", rootMeaning: "说", analysis: "de-(向下) + dic(说) + -ate → 宣誓 → 奉献", example: "She dedicates herself to teaching.", exampleCn: "她致力于教育事业。" },
  { word: "verdict", phonetic: "/ˈvɜːdɪkt/", meaning: "裁决；定论", pos: "n", root: "dict", rootMeaning: "说", analysis: "ver-(真实) + dict(说) → 真实地说 → 裁决", example: "The jury reached a verdict.", exampleCn: "陪审团做出了裁决。" },

  // ==================== port = 携带 ====================
  { word: "export", phonetic: "/ɪkˈspɔːt/", meaning: "出口；输出", pos: "v/n", root: "port", rootMeaning: "携带", analysis: "ex-(出) + port(携带) → 带出去 → 出口", example: "China exports many goods worldwide.", exampleCn: "中国向全球出口大量商品。" },
  { word: "import", phonetic: "/ɪmˈpɔːt/", meaning: "进口；输入", pos: "v/n", root: "port", rootMeaning: "携带", analysis: "im-(入) + port(携带) → 带进来 → 进口", example: "We import oil from the Middle East.", exampleCn: "我们从中东进口石油。" },
  { word: "transport", phonetic: "/trænˈspɔːt/", meaning: "运输；交通", pos: "v/n", root: "port", rootMeaning: "携带", analysis: "trans-(跨越) + port(携带) → 跨地携带 → 运输", example: "The goods were transported by truck.", exampleCn: "货物通过卡车运输。" },
  { word: "portable", phonetic: "/ˈpɔːtəbl/", meaning: "便携的", pos: "adj", root: "port", rootMeaning: "携带", analysis: "port(携带) + -able(能) → 能携带的 → 便携的", example: "A portable charger is very convenient.", exampleCn: "便携充电器非常方便。" },
  { word: "opportunity", phonetic: "/ˌɒpəˈtjuːnəti/", meaning: "机会", pos: "n", root: "port", rootMeaning: "携带", analysis: "op-(靠近) + port(携带) + -unity → 带到门前 → 机会", example: "Don't miss this opportunity.", exampleCn: "不要错过这个机会。" },

  // ==================== mit/miss = 送 ====================
  { word: "admit", phonetic: "/ədˈmɪt/", meaning: "承认；允许进入", pos: "v", root: "mit", rootMeaning: "送", analysis: "ad-(向) + mit(送) → 送入 → 承认", example: "He admitted his mistake.", exampleCn: "他承认了自己的错误。" },
  { word: "commit", phonetic: "/kəˈmɪt/", meaning: "承诺；犯(罪)", pos: "v", root: "mit", rootMeaning: "送", analysis: "com-(共同) + mit(送) → 送交 → 承诺", example: "We commit to finishing the work.", exampleCn: "我们承诺完成这项工作。" },
  { word: "permit", phonetic: "/pəˈmɪt/", meaning: "允许；许可", pos: "v/n", root: "mit", rootMeaning: "送", analysis: "per-(通过) + mit(送) → 放行 → 允许", example: "Smoking is not permitted here.", exampleCn: "此处不允许吸烟。" },
  { word: "submit", phonetic: "/səbˈmɪt/", meaning: "提交；服从", pos: "v", root: "mit", rootMeaning: "送", analysis: "sub-(下) + mit(送) → 从下送上 → 提交", example: "Please submit your report by Friday.", exampleCn: "请在周五前提交报告。" },
  { word: "transmit", phonetic: "/trænzˈmɪt/", meaning: "传播；传输", pos: "v", root: "mit", rootMeaning: "送", analysis: "trans-(跨越) + mit(送) → 跨距离送 → 传播", example: "The virus can transmit easily.", exampleCn: "该病毒易于传播。" },
  { word: "dismiss", phonetic: "/dɪsˈmɪs/", meaning: "解雇；驳回", pos: "v", root: "miss", rootMeaning: "送", analysis: "dis-(离开) + miss(送) → 送走 → 解雇", example: "He was dismissed from his job.", exampleCn: "他被解雇了。" },
  { word: "mission", phonetic: "/ˈmɪʃn/", meaning: "使命；任务", pos: "n", root: "miss", rootMeaning: "送", analysis: "miss(送) + -ion(名词) → 送出去的任务 → 使命", example: "Our mission is to help others.", exampleCn: "我们的使命是帮助他人。" },

  // ==================== duct/duc = 引导 ====================
  { word: "conduct", phonetic: "/kənˈdʌkt/", meaning: "进行；行为", pos: "v/n", root: "duct", rootMeaning: "引导", analysis: "con-(共同) + duct(引导) → 引导大家一起 → 进行", example: "They conducted an experiment.", exampleCn: "他们进行了一项实验。" },
  { word: "produce", phonetic: "/prəˈdjuːs/", meaning: "生产；制造", pos: "v", root: "duc", rootMeaning: "引导", analysis: "pro-(向前) + duc(引导) → 向前引导 → 生产", example: "The factory produces cars.", exampleCn: "这家工厂生产汽车。" },
  { word: "reduce", phonetic: "/rɪˈdjuːs/", meaning: "减少；降低", pos: "v", root: "duc", rootMeaning: "引导", analysis: "re-(回) + duc(引导) → 往回引 → 减少", example: "We need to reduce costs.", exampleCn: "我们需要降低成本。" },
  { word: "introduce", phonetic: "/ˌɪntrəˈdjuːs/", meaning: "介绍；引入", pos: "v", root: "duc", rootMeaning: "引导", analysis: "intro-(入) + duc(引导) → 引入 → 介绍", example: "Let me introduce myself.", exampleCn: "请允许我自我介绍。" },
  { word: "educate", phonetic: "/ˈedʒukeɪt/", meaning: "教育", pos: "v", root: "duc", rootMeaning: "引导", analysis: "e-(出) + duc(引导) + -ate → 引导出来 → 教育", example: "Parents should educate their children well.", exampleCn: "父母应好好教育孩子。" },
  { word: "deduct", phonetic: "/dɪˈdʌkt/", meaning: "扣除；减去", pos: "v", root: "duct", rootMeaning: "引导", analysis: "de-(向下) + duct(引导) → 向下引 → 扣除", example: "Tax is deducted from your salary.", exampleCn: "税款从工资中扣除。" },

  // ==================== scrib/script = 写 ====================
  { word: "describe", phonetic: "/dɪˈskraɪb/", meaning: "描述；形容", pos: "v", root: "scrib", rootMeaning: "写", analysis: "de-(向下) + scrib(写) → 写下来 → 描述", example: "Can you describe the accident?", exampleCn: "你能描述一下事故经过吗？" },
  { word: "prescribe", phonetic: "/prɪˈskraɪb/", meaning: "开药方；规定", pos: "v", root: "scrib", rootMeaning: "写", analysis: "pre-(预先) + scrib(写) → 预先写好 → 开药方", example: "The doctor prescribed some medicine.", exampleCn: "医生开了一些药。" },
  { word: "subscribe", phonetic: "/səbˈskraɪb/", meaning: "订阅；同意", pos: "v", root: "scrib", rootMeaning: "写", analysis: "sub-(下) + scrib(写) → 在下方写 → 订阅", example: "I subscribe to this magazine.", exampleCn: "我订阅了这本杂志。" },
  { word: "manuscript", phonetic: "/ˈmænjuskrɪpt/", meaning: "手稿；原稿", pos: "n", root: "script", rootMeaning: "写", analysis: "manu-(手) + script(写) → 手写的 → 手稿", example: "The author's manuscript was lost.", exampleCn: "作者的手稿丢失了。" },

  // ==================== struct = 建造 ====================
  { word: "construct", phonetic: "/kənˈstrʌkt/", meaning: "建造；构建", pos: "v", root: "struct", rootMeaning: "建造", analysis: "con-(共同) + struct(建造) → 共同建造 → 构建", example: "They constructed a new bridge.", exampleCn: "他们建造了一座新桥。" },
  { word: "destroy", phonetic: "/dɪˈstrɔɪ/", meaning: "破坏；摧毁", pos: "v", root: "struct", rootMeaning: "建造", analysis: "de-(除去) + stroy(struct) → 拆掉建筑 → 破坏", example: "The fire destroyed the building.", exampleCn: "大火摧毁了建筑。" },
  { word: "instruct", phonetic: "/ɪnˈstrʌkt/", meaning: "指导；指示", pos: "v", root: "struct", rootMeaning: "建造", analysis: "in-(向内) + struct(建造) → 在内心构建 → 指导", example: "The teacher instructs us in math.", exampleCn: "老师指导我们数学。" },
  { word: "structure", phonetic: "/ˈstrʌktʃə/", meaning: "结构；构造", pos: "n", root: "struct", rootMeaning: "建造", analysis: "struct(建造) + -ure(名词) → 建造出来的 → 结构", example: "The structure of the essay is clear.", exampleCn: "文章的结构很清晰。" },
  { word: "obstacle", phonetic: "/ˈɒbstəkl/", meaning: "障碍", pos: "n", root: "struct", rootMeaning: "建造", analysis: "ob-(反) + sta(站立) + -cle → 站在对面 → 障碍", example: "Lack of money is a major obstacle.", exampleCn: "缺钱是主要障碍。" },

  // ==================== tract = 拉 ====================
  { word: "attract", phonetic: "/əˈtrækt/", meaning: "吸引", pos: "v", root: "tract", rootMeaning: "拉", analysis: "at-(向) + tract(拉) → 拉向 → 吸引", example: "The exhibition attracted many visitors.", exampleCn: "展览吸引了许多参观者。" },
  { word: "contract", phonetic: "/ˈkɒntrækt/", meaning: "合同；收缩", pos: "n/v", root: "tract", rootMeaning: "拉", analysis: "con-(共同) + tract(拉) → 拉到一起 → 合同", example: "We signed a contract with the company.", exampleCn: "我们与公司签订了合同。" },
  { word: "extract", phonetic: "/ɪkˈstrækt/", meaning: "提取；摘录", pos: "v", root: "tract", rootMeaning: "拉", analysis: "ex-(出) + tract(拉) → 拉出来 → 提取", example: "They extract oil from seeds.", exampleCn: "他们从种子中提取油。" },
  { word: "distract", phonetic: "/dɪˈstrækt/", meaning: "分散注意力；分心", pos: "v", root: "tract", rootMeaning: "拉", analysis: "dis-(分开) + tract(拉) → 拉开 → 分心", example: "Don't distract me while I'm working.", exampleCn: "我工作时不要打扰我。" },
  { word: "subtract", phonetic: "/səbˈtrækt/", meaning: "减去；扣除", pos: "v", root: "tract", rootMeaning: "拉", analysis: "sub-(下) + tract(拉) → 向下拉 → 减去", example: "Subtract 3 from 10 and you get 7.", exampleCn: "10减3等于7。" },

  // ==================== vert/vers = 转 ====================
  { word: "convert", phonetic: "/kənˈvɜːt/", meaning: "转变；转换", pos: "v", root: "vert", rootMeaning: "转", analysis: "con-(完全) + vert(转) → 完全转变 → 转换", example: "They converted the garage into a study.", exampleCn: "他们把车库改成了书房。" },
  { word: "diverse", phonetic: "/daɪˈvɜːs/", meaning: "多样的；不同的", pos: "adj", root: "vers", rootMeaning: "转", analysis: "di-(分开) + vers(转) → 转向不同方向 → 多样的", example: "Our school has a diverse student body.", exampleCn: "我们学校学生群体多元化。" },
  { word: "reverse", phonetic: "/rɪˈvɜːs/", meaning: "相反的；逆转", pos: "v/adj", root: "vers", rootMeaning: "转", analysis: "re-(回) + vers(转) → 转回去 → 逆转", example: "The car reversed into the garage.", exampleCn: "汽车倒进车库。" },
  { word: "universe", phonetic: "/ˈjuːnɪvɜːs/", meaning: "宇宙", pos: "n", root: "vers", rootMeaning: "转", analysis: "uni-(一) + vers(转) → 统一旋转的 → 宇宙", example: "The universe is vast.", exampleCn: "宇宙浩瀚无垠。" },
  { word: "advertise", phonetic: "/ˈædvətaɪz/", meaning: "做广告", pos: "v", root: "vert", rootMeaning: "转", analysis: "ad-(向) + vert(转) + -ise → 让人注意力转向 → 做广告", example: "They advertise their products online.", exampleCn: "他们在网上为产品做广告。" },
  { word: "controversy", phonetic: "/ˈkɒntrəvɜːsi/", meaning: "争论；争议", pos: "n", root: "vers", rootMeaning: "转", analysis: "contro-(相对) + vers(转) + -y → 转向对面 → 争论", example: "The issue caused a lot of controversy.", exampleCn: "这个问题引起了很多争议。" },

  // ==================== form = 形状 ====================
  { word: "conform", phonetic: "/kənˈfɔːm/", meaning: "遵守；符合", pos: "v", root: "form", rootMeaning: "形状", analysis: "con-(共同) + form(形状) → 形状一致 → 符合", example: "You must conform to the rules.", exampleCn: "你必须遵守规则。" },
  { word: "inform", phonetic: "/ɪnˈfɔːm/", meaning: "通知；告知", pos: "v", root: "form", rootMeaning: "形状", analysis: "in-(入) + form(形状) → 进入形态 → 通知", example: "Please inform us of any changes.", exampleCn: "如有变化请通知我们。" },
  { word: "perform", phonetic: "/pəˈfɔːm/", meaning: "执行；表演；表现", pos: "v", root: "form", rootMeaning: "形状", analysis: "per-(完全) + form(形状) → 完全成形 → 执行", example: "She performed well in the exam.", exampleCn: "她在考试中表现很好。" },
  { word: "reform", phonetic: "/rɪˈfɔːm/", meaning: "改革；改良", pos: "v/n", root: "form", rootMeaning: "形状", analysis: "re-(再) + form(形状) → 重新塑形 → 改革", example: "The government plans to reform the system.", exampleCn: "政府计划改革制度。" },
  { word: "transform", phonetic: "/trænsˈfɔːm/", meaning: "改变；转变", pos: "v", root: "form", rootMeaning: "形状", analysis: "trans-(跨越) + form(形状) → 变形 → 改变", example: "Technology has transformed our lives.", exampleCn: "科技改变了我们的生活。" },
  { word: "uniform", phonetic: "/ˈjuːnɪfɔːm/", meaning: "制服；统一的", pos: "n/adj", root: "form", rootMeaning: "形状", analysis: "uni-(一) + form(形状) → 一种形状 → 统一的", example: "Students wear uniforms to school.", exampleCn: "学生穿校服上学。" },

  // ==================== cede/ceed/cess = 走 ====================
  { word: "exceed", phonetic: "/ɪkˈsiːd/", meaning: "超过；超越", pos: "v", root: "ceed", rootMeaning: "走", analysis: "ex-(出) + ceed(走) → 走出 → 超过", example: "Don't exceed the speed limit.", exampleCn: "不要超过限速。" },
  { word: "proceed", phonetic: "/prəˈsiːd/", meaning: "继续；进行", pos: "v", root: "ceed", rootMeaning: "走", analysis: "pro-(向前) + ceed(走) → 向前走 → 继续", example: "Let's proceed with the plan.", exampleCn: "让我们继续执行计划。" },
  { word: "succeed", phonetic: "/səkˈsiːd/", meaning: "成功", pos: "v", root: "ceed", rootMeaning: "走", analysis: "suc-(下) + ceed(走) → 一直走下去 → 成功", example: "If you work hard, you will succeed.", exampleCn: "努力就会成功。" },
  { word: "access", phonetic: "/ˈækses/", meaning: "进入；通道；访问", pos: "n/v", root: "cess", rootMeaning: "走", analysis: "ac-(向) + cess(走) → 走向 → 进入", example: "Students have access to the library.", exampleCn: "学生可以使用图书馆。" },
  { word: "process", phonetic: "/ˈprəʊses/", meaning: "过程；处理", pos: "n/v", root: "cess", rootMeaning: "走", analysis: "pro-(向前) + cess(走) → 向前走 → 过程", example: "Learning is a long process.", exampleCn: "学习是一个漫长的过程。" },
  { word: "recession", phonetic: "/rɪˈseʃn/", meaning: "衰退；萧条", pos: "n", root: "cess", rootMeaning: "走", analysis: "re-(回) + cess(走) + -ion → 往回走 → 衰退", example: "The economy is in a recession.", exampleCn: "经济处于衰退期。" },

  // ==================== tain/ten = 持有 ====================
  { word: "contain", phonetic: "/kənˈteɪn/", meaning: "包含；容纳", pos: "v", root: "tain", rootMeaning: "持有", analysis: "con-(共同) + tain(持有) → 共同持有 → 包含", example: "This book contains useful information.", exampleCn: "这本书包含有用的信息。" },
  { word: "maintain", phonetic: "/meɪnˈteɪn/", meaning: "维持；保养", pos: "v", root: "tain", rootMeaning: "持有", analysis: "main-(手) + tain(持有) → 握在手中 → 维持", example: "We should maintain good habits.", exampleCn: "我们应该保持良好的习惯。" },
  { word: "obtain", phonetic: "/əbˈteɪn/", meaning: "获得；得到", pos: "v", root: "tain", rootMeaning: "持有", analysis: "ob-(加强) + tain(持有) → 拿到 → 获得", example: "She obtained a degree in engineering.", exampleCn: "她获得了工程学位。" },
  { word: "sustain", phonetic: "/səˈsteɪn/", meaning: "维持；支撑", pos: "v", root: "tain", rootMeaning: "持有", analysis: "sus-(下) + tain(持有) → 在下方支撑 → 维持", example: "We need to sustain economic growth.", exampleCn: "我们需要维持经济增长。" },
  { word: "content", phonetic: "/ˈkɒntent/", meaning: "内容；满足的", pos: "n/adj", root: "ten", rootMeaning: "持有", analysis: "con-(共同) + ten(持有) → 容纳在一起 → 内容", example: "The content of the article is interesting.", exampleCn: "这篇文章的内容很有趣。" },
  { word: "continue", phonetic: "/kənˈtɪnjuː/", meaning: "继续", pos: "v", root: "ten", rootMeaning: "持有", analysis: "con-(共同) + tin(持有) + -ue → 一直持有 → 继续", example: "Let's continue our discussion.", exampleCn: "让我们继续讨论。" },

  // ==================== cap/cept = 拿 ====================
  { word: "accept", phonetic: "/əkˈsept/", meaning: "接受", pos: "v", root: "cept", rootMeaning: "拿", analysis: "ac-(向) + cept(拿) → 去拿 → 接受", example: "I accept your invitation.", exampleCn: "我接受你的邀请。" },
  { word: "concept", phonetic: "/ˈkɒnsept/", meaning: "概念；观念", pos: "n", root: "cept", rootMeaning: "拿", analysis: "con-(共同) + cept(拿) → 共同把握 → 概念", example: "It's a difficult concept to understand.", exampleCn: "这是一个难以理解的概念。" },
  { word: "except", phonetic: "/ɪkˈsept/", meaning: "除了", pos: "prep", root: "cept", rootMeaning: "拿", analysis: "ex-(出) + cept(拿) → 拿出去 → 排除", example: "Everyone came except Tom.", exampleCn: "除了Tom，大家都来了。" },
  { word: "perceive", phonetic: "/pəˈsiːv/", meaning: "感知；察觉", pos: "v", root: "cept", rootMeaning: "拿", analysis: "per-(完全) + ceive(cept) → 完全拿到 → 感知", example: "I perceived a change in his attitude.", exampleCn: "我察觉到他态度有变化。" },
  { word: "receive", phonetic: "/rɪˈsiːv/", meaning: "收到；接收", pos: "v", root: "cept", rootMeaning: "拿", analysis: "re-(回) + ceive(cept) → 拿回来 → 收到", example: "I received a letter from my friend.", exampleCn: "我收到了朋友的来信。" },
  { word: "capture", phonetic: "/ˈkæptʃə/", meaning: "捕获；俘获", pos: "v/n", root: "cap", rootMeaning: "拿", analysis: "cap(拿) + -ture(名词) → 拿住 → 捕获", example: "The police captured the criminal.", exampleCn: "警察捕获了罪犯。" },

  // ==================== fact/fect = 做 ====================
  { word: "affect", phonetic: "/əˈfekt/", meaning: "影响", pos: "v", root: "fect", rootMeaning: "做", analysis: "af-(向) + fect(做) → 对…做 → 影响", example: "Smoking affects your health.", exampleCn: "吸烟影响健康。" },
  { word: "effect", phonetic: "/ɪˈfekt/", meaning: "效果；影响", pos: "n", root: "fect", rootMeaning: "做", analysis: "ef-(出) + fect(做) → 做出来的结果 → 效果", example: "The new law took effect last month.", exampleCn: "新法律上个月生效了。" },
  { word: "perfect", phonetic: "/ˈpɜːfɪkt/", meaning: "完美的；完美的", pos: "adj", root: "fect", rootMeaning: "做", analysis: "per-(完全) + fect(做) → 完全做好 → 完美的", example: "Practice makes perfect.", exampleCn: "熟能生巧。" },
  { word: "manufacture", phonetic: "/ˌmænjuˈfæktʃə/", meaning: "制造；生产", pos: "v/n", root: "fact", rootMeaning: "做", analysis: "manu-(手) + fact(做) + -ure → 用手做 → 制造", example: "The company manufactures computers.", exampleCn: "这家公司制造电脑。" },
  { word: "defect", phonetic: "/ˈdiːfekt/", meaning: "缺陷；缺点", pos: "n", root: "fect", rootMeaning: "做", analysis: "de-(坏) + fect(做) → 做坏了 → 缺陷", example: "The product has a defect.", exampleCn: "这个产品有缺陷。" },
  { word: "efficient", phonetic: "/ɪˈfɪʃnt/", meaning: "高效的", pos: "adj", root: "fect", rootMeaning: "做", analysis: "ef-(出) + fici(fect) + -ent → 快速做出 → 高效的", example: "This method is very efficient.", exampleCn: "这个方法非常高效。" },

  // ==================== vid/vis = 看 ====================
  { word: "evident", phonetic: "/ˈevɪdənt/", meaning: "明显的；显然的", pos: "adj", root: "vid", rootMeaning: "看", analysis: "e-(出) + vid(看) + -ent → 看得出来 → 明显的", example: "It's evident that he is upset.", exampleCn: "显然他很不高兴。" },
  { word: "provide", phonetic: "/prəˈvaɪd/", meaning: "提供", pos: "v", root: "vid", rootMeaning: "看", analysis: "pro-(向前) + vid(看) → 提前看到 → 提供", example: "The hotel provides free breakfast.", exampleCn: "酒店提供免费早餐。" },
  { word: "vision", phonetic: "/ˈvɪʒn/", meaning: "视力；愿景", pos: "n", root: "vis", rootMeaning: "看", analysis: "vis(看) + -ion(名词) → 看的能力 → 视力", example: "He has a clear vision for the future.", exampleCn: "他对未来有清晰的愿景。" },
  { word: "revise", phonetic: "/rɪˈvaɪz/", meaning: "修订；复习", pos: "v", root: "vis", rootMeaning: "看", analysis: "re-(再) + vis(看) → 再看一遍 → 修订", example: "I need to revise for the exam.", exampleCn: "我需要为考试复习。" },
  { word: "supervise", phonetic: "/ˈsuːpəvaɪz/", meaning: "监督；管理", pos: "v", root: "vis", rootMeaning: "看", analysis: "super-(上) + vis(看) → 从上往下看 → 监督", example: "The manager supervises our work.", exampleCn: "经理监督我们的工作。" },

  // ==================== pel/puls = 推动 ====================
  { word: "compel", phonetic: "/kəmˈpel/", meaning: "强迫；迫使", pos: "v", root: "pel", rootMeaning: "推动", analysis: "com-(加强) + pel(推) → 用力推 → 强迫", example: "The law compels us to pay taxes.", exampleCn: "法律强制我们纳税。" },
  { word: "expel", phonetic: "/ɪkˈspel/", meaning: "驱逐；开除", pos: "v", root: "pel", rootMeaning: "推动", analysis: "ex-(出) + pel(推) → 推出去 → 驱逐", example: "He was expelled from school.", exampleCn: "他被学校开除了。" },
  { word: "impulse", phonetic: "/ˈɪmpʌls/", meaning: "冲动；推动力", pos: "n", root: "puls", rootMeaning: "推动", analysis: "im-(内) + puls(推) → 内部推动 → 冲动", example: "He bought the car on impulse.", exampleCn: "他一时冲动买了那辆车。" },

  // ==================== voc/vok = 呼唤 ====================
  { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "提倡；拥护", pos: "v/n", root: "voc", rootMeaning: "呼唤", analysis: "ad-(向) + voc(呼唤) + -ate → 向…呼唤 → 提倡", example: "He advocates for environmental protection.", exampleCn: "他提倡环境保护。" },
  { word: "provoke", phonetic: "/prəˈvəʊk/", meaning: "激起；激怒", pos: "v", root: "vok", rootMeaning: "呼唤", analysis: "pro-(向前) + vok(呼唤) → 向前呼唤 → 激起", example: "His remarks provoked anger.", exampleCn: "他的言论激起了愤怒。" },

  // ==================== log = 言语/学科 ====================
  { word: "apology", phonetic: "/əˈpɒlədʒi/", meaning: "道歉", pos: "n", root: "log", rootMeaning: "言语", analysis: "apo-(离开) + log(言语) + -y → 脱罪之言 → 道歉", example: "He made an apology for his mistake.", exampleCn: "他为自己的错误道了歉。" },
  { word: "dialogue", phonetic: "/ˈdaɪəlɒɡ/", meaning: "对话", pos: "n", root: "log", rootMeaning: "言语", analysis: "dia-(对) + logue(言语) → 两人言语 → 对话", example: "The dialogue between the two leaders was positive.", exampleCn: "两位领导人的对话是积极的。" },
  { word: "logic", phonetic: "/ˈlɒdʒɪk/", meaning: "逻辑", pos: "n", root: "log", rootMeaning: "言语", analysis: "log(言语/推理) + -ic → 推理之学 → 逻辑", example: "There's no logic in his argument.", exampleCn: "他的论证毫无逻辑。" },
  { word: "biology", phonetic: "/baɪˈɒlədʒi/", meaning: "生物学", pos: "n", root: "log", rootMeaning: "学科", analysis: "bio-(生命) + log(学科) + -y → 生命学科 → 生物学", example: "She's studying biology at university.", exampleCn: "她在大学学生物学。" },

  // ==================== graph = 写 ====================
  { word: "biography", phonetic: "/baɪˈɒɡrəfi/", meaning: "传记", pos: "n", root: "graph", rootMeaning: "写", analysis: "bio-(生命) + graph(写) + -y → 写一生 → 传记", example: "I read a biography of Lincoln.", exampleCn: "我读了林肯的传记。" },
  { word: "geography", phonetic: "/dʒiˈɒɡrəfi/", meaning: "地理", pos: "n", root: "graph", rootMeaning: "写", analysis: "geo-(地) + graph(写) + -y → 写大地 → 地理", example: "Geography is my favorite subject.", exampleCn: "地理是我最喜欢的科目。" },
  { word: "paragraph", phonetic: "/ˈpærəɡrɑːf/", meaning: "段落", pos: "n", root: "graph", rootMeaning: "写", analysis: "para-(旁) + graph(写) → 旁写 → 段落", example: "Write a paragraph about your hobby.", exampleCn: "写一段关于你爱好的文字。" },

  // ==================== rupt = 破 ====================
  { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "突然的；唐突的", pos: "adj", root: "rupt", rootMeaning: "破", analysis: "ab-(离开) + rupt(破) → 断开 → 突然的", example: "The meeting came to an abrupt end.", exampleCn: "会议突然结束了。" },
  { word: "corrupt", phonetic: "/kəˈrʌpt/", meaning: "腐败的；贪污的", pos: "adj/v", root: "rupt", rootMeaning: "破", analysis: "cor-(完全) + rupt(破) → 完全破坏 → 腐败的", example: "The corrupt official was arrested.", exampleCn: "那个腐败官员被捕了。" },
  { word: "disrupt", phonetic: "/dɪsˈrʌpt/", meaning: "扰乱；中断", pos: "v", root: "rupt", rootMeaning: "破", analysis: "dis-(分开) + rupt(破) → 破开 → 扰乱", example: "The storm disrupted our travel plans.", exampleCn: "暴风雨打乱了我们的旅行计划。" },
  { word: "interrupt", phonetic: "/ˌɪntəˈrʌpt/", meaning: "打断；中断", pos: "v", root: "rupt", rootMeaning: "破", analysis: "inter-(中间) + rupt(破) → 从中破开 → 打断", example: "Please don't interrupt me.", exampleCn: "请不要打断我。" },

  // ==================== ject = 投掷 ====================
  { word: "inject", phonetic: "/ɪnˈdʒekt/", meaning: "注射；注入", pos: "v", root: "ject", rootMeaning: "投掷", analysis: "in-(入) + ject(投掷) → 投入 → 注射", example: "The nurse injected the vaccine.", exampleCn: "护士注射了疫苗。" },
  { word: "object", phonetic: "/ˈɒbdʒɪkt/", meaning: "物体；目标；反对", pos: "n/v", root: "ject", rootMeaning: "投掷", analysis: "ob-(前) + ject(投掷) → 投到前面 → 目标", example: "What is the object of this exercise?", exampleCn: "这个练习的目的是什么？" },
  { word: "project", phonetic: "/ˈprɒdʒekt/", meaning: "项目；投射", pos: "n/v", root: "ject", rootMeaning: "投掷", analysis: "pro-(向前) + ject(投掷) → 向前扔 → 项目", example: "We are working on a new project.", exampleCn: "我们正在做一个新项目。" },
  { word: "reject", phonetic: "/rɪˈdʒekt/", meaning: "拒绝；排斥", pos: "v", root: "ject", rootMeaning: "投掷", analysis: "re-(回) + ject(投掷) → 扔回去 → 拒绝", example: "His application was rejected.", exampleCn: "他的申请被拒绝了。" },
  { word: "subject", phonetic: "/ˈsʌbdʒɪkt/", meaning: "主题；科目；受…支配的", pos: "n/v/adj", root: "ject", rootMeaning: "投掷", analysis: "sub-(下) + ject(投掷) → 置于下方 → 受支配的", example: "What's your favorite subject?", exampleCn: "你最喜欢的科目是什么？" },

  // ==================== ven/vent = 来 ====================
  { word: "adventure", phonetic: "/ədˈventʃə/", meaning: "冒险；奇遇", pos: "n", root: "vent", rootMeaning: "来", analysis: "ad-(向) + vent(来) + -ure → 走向未知 → 冒险", example: "Life is an adventure.", exampleCn: "生活是一次冒险。" },
  { word: "convention", phonetic: "/kənˈvenʃn/", meaning: "传统；大会", pos: "n", root: "vent", rootMeaning: "来", analysis: "con-(共同) + vent(来) + -ion → 走到一起 → 大会", example: "By convention, we shake hands.", exampleCn: "按惯例我们握手。" },
  { word: "event", phonetic: "/ɪˈvent/", meaning: "事件；大事", pos: "n", root: "vent", rootMeaning: "来", analysis: "e-(出) + vent(来) → 出来的事情 → 事件", example: "The Olympics is a major sporting event.", exampleCn: "奥运会是重大的体育赛事。" },
  { word: "invent", phonetic: "/ɪnˈvent/", meaning: "发明；创造", pos: "v", root: "vent", rootMeaning: "来", analysis: "in-(入) + vent(来) → 走入新领域 → 发明", example: "Edison invented the light bulb.", exampleCn: "爱迪生发明了电灯泡。" },
  { word: "prevent", phonetic: "/prɪˈvent/", meaning: "防止；预防", pos: "v", root: "vent", rootMeaning: "来", analysis: "pre-(先) + vent(来) → 先来一步 → 预防", example: "Eating well can prevent many diseases.", exampleCn: "吃得好可以预防许多疾病。" },

  // ==================== mot/mov = 移动 ====================
  { word: "emotion", phonetic: "/ɪˈməʊʃn/", meaning: "情感；情绪", pos: "n", root: "mot", rootMeaning: "移动", analysis: "e-(出) + mot(移动) + -ion → 内心的移动 → 情感", example: "She showed no emotion.", exampleCn: "她没有表现出任何情绪。" },
  { word: "motive", phonetic: "/ˈməʊtɪv/", meaning: "动机；目的", pos: "n", root: "mot", rootMeaning: "移动", analysis: "mot(移动) + -ive → 让人动起来的 → 动机", example: "What's his motive for lying?", exampleCn: "他撒谎的动机是什么？" },
  { word: "promote", phonetic: "/prəˈməʊt/", meaning: "推广；提升；促进", pos: "v", root: "mot", rootMeaning: "移动", analysis: "pro-(向前) + mot(移动) → 向前移动 → 提升", example: "Exercise promotes good health.", exampleCn: "运动促进健康。" },
  { word: "remote", phonetic: "/rɪˈməʊt/", meaning: "遥远的；远程的", pos: "adj", root: "mot", rootMeaning: "移动", analysis: "re-(回) + mot(移动) → 向后移动 → 遥远的", example: "They live in a remote village.", exampleCn: "他们住在一个偏远的村庄。" },
  { word: "remove", phonetic: "/rɪˈmuːv/", meaning: "移除；删除", pos: "v", root: "mov", rootMeaning: "移动", analysis: "re-(回) + mov(移动) → 移走 → 移除", example: "Please remove your shoes.", exampleCn: "请脱掉鞋子。" },

  // ==================== pos/pon = 放置 ====================
  { word: "compose", phonetic: "/kəmˈpəʊz/", meaning: "组成；作曲；写作", pos: "v", root: "pos", rootMeaning: "放置", analysis: "com-(共同) + pos(放置) → 放在一起 → 组成", example: "The team is composed of 11 players.", exampleCn: "队伍由11名球员组成。" },
  { word: "deposit", phonetic: "/dɪˈpɒzɪt/", meaning: "存放；存款", pos: "v/n", root: "pos", rootMeaning: "放置", analysis: "de-(向下) + pos(放置) + -it → 放下 → 存放", example: "I deposited money in the bank.", exampleCn: "我在银行存了钱。" },
  { word: "expose", phonetic: "/ɪkˈspəʊz/", meaning: "暴露；揭露", pos: "v", root: "pos", rootMeaning: "放置", analysis: "ex-(出) + pos(放置) → 放在外面 → 暴露", example: "Don't expose your skin to the sun.", exampleCn: "不要让皮肤暴露在阳光下。" },
  { word: "impose", phonetic: "/ɪmˈpəʊz/", meaning: "强加；征税", pos: "v", root: "pos", rootMeaning: "放置", analysis: "im-(上) + pos(放置) → 放在上面 → 强加", example: "Don't impose your views on others.", exampleCn: "不要把你的观点强加于人。" },
  { word: "oppose", phonetic: "/əˈpəʊz/", meaning: "反对；对抗", pos: "v", root: "pos", rootMeaning: "放置", analysis: "op-(反) + pos(放置) → 放在对面 → 反对", example: "Many people oppose the plan.", exampleCn: "许多人反对这个计划。" },
  { word: "propose", phonetic: "/prəˈpəʊz/", meaning: "提议；建议；求婚", pos: "v", root: "pos", rootMeaning: "放置", analysis: "pro-(向前) + pos(放置) → 向前放 → 提议", example: "I propose we take a break.", exampleCn: "我建议我们休息一下。" },
  { word: "suppose", phonetic: "/səˈpəʊz/", meaning: "假设；认为", pos: "v", root: "pos", rootMeaning: "放置", analysis: "sup-(下) + pos(放置) → 放在下面 → 假设", example: "I suppose you're right.", exampleCn: "我想你是对的。" },

  // ==================== 常用前缀词 ====================
  { word: "preview", phonetic: "/ˈpriːvjuː/", meaning: "预览", pos: "v/n", root: "pre-", rootMeaning: "前/预", analysis: "pre-(预) + view(看) → 预先看 → 预览", example: "Let's preview the video before publishing.", exampleCn: "发布前我们先预览一下视频。" },
  { word: "precaution", phonetic: "/prɪˈkɔːʃn/", meaning: "预防；警惕", pos: "n", root: "pre-", rootMeaning: "前/预", analysis: "pre-(预) + caution(小心) → 预先小心 → 预防", example: "Take precautions against fire.", exampleCn: "采取防火措施。" },
  { word: "subway", phonetic: "/ˈsʌbweɪ/", meaning: "地铁", pos: "n", root: "sub-", rootMeaning: "下", analysis: "sub-(下) + way(路) → 地下的路 → 地铁", example: "I take the subway to work.", exampleCn: "我坐地铁上班。" },
  { word: "substitute", phonetic: "/ˈsʌbstɪtjuːt/", meaning: "替代；替补", pos: "v/n", root: "sub-", rootMeaning: "下", analysis: "sub-(下) + stitute(站立) → 站在下面 → 替补", example: "There's no substitute for hard work.", exampleCn: "努力没有替代品。" },
  { word: "interact", phonetic: "/ˌɪntərˈækt/", meaning: "互动；相互作用", pos: "v", root: "inter-", rootMeaning: "之间", analysis: "inter-(之间) + act(行动) → 之间互动 → 互动", example: "Teachers should interact with students.", exampleCn: "老师应该与学生互动。" },
  { word: "international", phonetic: "/ˌɪntəˈnæʃnəl/", meaning: "国际的", pos: "adj", root: "inter-", rootMeaning: "之间", analysis: "inter-(之间) + nation(国家) + -al → 国家之间的 → 国际的", example: "English is an international language.", exampleCn: "英语是国际语言。" },
  { word: "transfer", phonetic: "/trænsˈfɜː/", meaning: "转移；转让；调动", pos: "v/n", root: "trans-", rootMeaning: "跨越", analysis: "trans-(跨越) + fer(带) → 带过去 → 转移", example: "He transferred to another school.", exampleCn: "他转到了另一所学校。" },
  { word: "translate", phonetic: "/trænzˈleɪt/", meaning: "翻译", pos: "v", root: "trans-", rootMeaning: "跨越", analysis: "trans-(跨越) + late(带) → 跨语言传递 → 翻译", example: "Can you translate this into English?", exampleCn: "你能把这个翻译成英语吗？" },
  { word: "cooperate", phonetic: "/kəʊˈɒpəreɪt/", meaning: "合作", pos: "v", root: "co-", rootMeaning: "共同", analysis: "co-(共同) + operate(运作) → 共同运作 → 合作", example: "We should cooperate with each other.", exampleCn: "我们应该互相合作。" },
  { word: "coexist", phonetic: "/ˌkəʊɪɡˈzɪst/", meaning: "共存", pos: "v", root: "co-", rootMeaning: "共同", analysis: "co-(共同) + exist(存在) → 共同存在 → 共存", example: "Different cultures can coexist peacefully.", exampleCn: "不同文化可以和平共存。" },
  { word: "dislike", phonetic: "/dɪsˈlaɪk/", meaning: "不喜欢", pos: "v", root: "dis-", rootMeaning: "不/相反", analysis: "dis-(不) + like(喜欢) → 不喜欢", example: "I dislike rude people.", exampleCn: "我不喜欢粗鲁的人。" },
  { word: "disappear", phonetic: "/ˌdɪsəˈpɪə/", meaning: "消失", pos: "v", root: "dis-", rootMeaning: "不/相反", analysis: "dis-(不) + appear(出现) → 不出现 → 消失", example: "The sun disappeared behind a cloud.", exampleCn: "太阳消失在云层后面。" },
  { word: "enable", phonetic: "/ɪˈneɪbl/", meaning: "使能够", pos: "v", root: "en-", rootMeaning: "使", analysis: "en-(使) + able(能够) → 使能够", example: "This app enables you to learn English.", exampleCn: "这个应用让你能学英语。" },
  { word: "enrich", phonetic: "/ɪnˈrɪtʃ/", meaning: "丰富；充实", pos: "v", root: "en-", rootMeaning: "使", analysis: "en-(使) + rich(富有的) → 使富有 → 充实", example: "Reading enriches your mind.", exampleCn: "阅读充实你的心灵。" },
  { word: "overcome", phonetic: "/ˌəʊvəˈkʌm/", meaning: "克服；战胜", pos: "v", root: "over-", rootMeaning: "超过", analysis: "over-(超过) + come(来) → 超过并过来 → 克服", verbForms: { past: "overcame", pastParticiple: "overcome", presentParticiple: "overcoming" }, example: "We must overcome our fears.", exampleCn: "我们必须克服恐惧。" },
  { word: "overlook", phonetic: "/ˌəʊvəˈlʊk/", meaning: "忽视；俯瞰", pos: "v", root: "over-", rootMeaning: "超过", analysis: "over-(过) + look(看) → 看过去 → 忽视", example: "Don't overlook the details.", exampleCn: "不要忽视细节。" },
  { word: "misunderstand", phonetic: "/ˌmɪsʌndəˈstænd/", meaning: "误解", pos: "v", root: "mis-", rootMeaning: "错误", analysis: "mis-(错) + understand(理解) → 错误理解 → 误解", verbForms: { past: "misunderstood", pastParticiple: "misunderstood", presentParticiple: "misunderstanding" }, example: "I think you misunderstood me.", exampleCn: "我想你误解我了。" },
  { word: "mislead", phonetic: "/ˌmɪsˈliːd/", meaning: "误导", pos: "v", root: "mis-", rootMeaning: "错误", analysis: "mis-(错) + lead(引导) → 错误引导 → 误导", verbForms: { past: "misled", pastParticiple: "misled", presentParticiple: "misleading" }, example: "Don't be misled by false advertising.", exampleCn: "不要被虚假广告误导。" },

  // ==================== 补充高频词 ====================
  { word: "abandon", phonetic: "/əˈbændən/", meaning: "放弃；抛弃", pos: "v", root: "a-", rootMeaning: "否定", analysis: "a-(不) + band(绑) + -on → 不再绑着 → 放弃", example: "Never abandon your dreams.", exampleCn: "永远不要放弃你的梦想。" },
  { word: "absorb", phonetic: "/əbˈzɔːb/", meaning: "吸收；吸引", pos: "v", root: "ab-", rootMeaning: "离去", analysis: "ab-(离开) + sorb(吸) → 吸走 → 吸收", example: "Plants absorb water from the soil.", exampleCn: "植物从土壤中吸收水分。" },
  { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "抽象的；摘要", pos: "adj/n", root: "tract", rootMeaning: "拉", analysis: "abs-(离开) + tract(拉) → 拉开 → 抽象的", example: "Abstract art is sometimes hard to understand.", exampleCn: "抽象艺术有时很难理解。" },
  { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "丰富的；充裕的", pos: "adj", root: "und", rootMeaning: "波浪", analysis: "ab-(离) + und(波浪) + -ant → 波浪般涌来 → 丰富的", example: "This region has abundant natural resources.", exampleCn: "这个地区有丰富的自然资源。" },
  { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "陪伴；伴随", pos: "v", root: "com-", rootMeaning: "共同", analysis: "ac-(向) + company(陪伴) → 陪伴", example: "I'll accompany you to the station.", exampleCn: "我陪你去车站。" },
  { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "完成；达成", pos: "v", root: "com-", rootMeaning: "完全", analysis: "ac-(向) + com(完全) + pli(填满) + -ish → 填满 → 完成", example: "We accomplished our goal.", exampleCn: "我们完成了目标。" },
  { word: "accurate", phonetic: "/ˈækjərət/", meaning: "准确的；精确的", pos: "adj", root: "cur", rootMeaning: "关心", analysis: "ac-(向) + cur(关心) + -ate → 细心 → 准确的", example: "Make sure your data is accurate.", exampleCn: "确保你的数据准确。" },
  { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "承认；确认", pos: "v", root: "know", rootMeaning: "知道", analysis: "ac-(向) + knowledge(知识) → 去知道 → 承认", example: "She acknowledged her mistake.", exampleCn: "她承认了自己的错误。" },
  { word: "acquire", phonetic: "/əˈkwaɪə/", meaning: "获得；习得", pos: "v", root: "quir", rootMeaning: "寻求", analysis: "ac-(向) + quir(寻求) → 寻求到 → 获得", example: "She acquired a good knowledge of English.", exampleCn: "她英语学得很好。" },
  { word: "adapt", phonetic: "/əˈdæpt/", meaning: "适应；改编", pos: "v", root: "apt", rootMeaning: "适合", analysis: "ad-(向) + apt(适合) → 使适合 → 适应", example: "You need to adapt to the new environment.", exampleCn: "你需要适应新环境。" },
  { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "足够的；适当的", pos: "adj", root: "equ", rootMeaning: "相等", analysis: "ad-(向) + equ(相等) + -ate → 与要求相等 → 足够的", example: "We don't have adequate time to prepare.", exampleCn: "我们没有足够的时间准备。" },
  { word: "adjust", phonetic: "/əˈdʒʌst/", meaning: "调整；适应", pos: "v", root: "just", rootMeaning: "正确", analysis: "ad-(向) + just(正确) → 朝正确的方向 → 调整", example: "You can adjust the volume with this button.", exampleCn: "你可以用这个按钮调节音量。" },
  { word: "admire", phonetic: "/ədˈmaɪə/", meaning: "钦佩；赞美", pos: "v", root: "mir", rootMeaning: "惊奇", analysis: "ad-(向) + mir(惊奇) → 对…惊奇 → 钦佩", example: "I admire her courage.", exampleCn: "我钦佩她的勇气。" },
  { word: "adopt", phonetic: "/əˈdɒpt/", meaning: "采用；收养", pos: "v", root: "opt", rootMeaning: "选择", analysis: "ad-(向) + opt(选择) → 选择 → 采用", example: "We adopted a new approach.", exampleCn: "我们采用了一种新方法。" },
  { word: "alternative", phonetic: "/ɔːlˈtɜːnətɪv/", meaning: "替代方案；供选择的", pos: "n/adj", root: "alter", rootMeaning: "其他", analysis: "alter(其他) + -native → 其他的选择 → 替代方案", example: "We need to find an alternative solution.", exampleCn: "我们需要找到替代方案。" },
  { word: "analyze", phonetic: "/ˈænəlaɪz/", meaning: "分析", pos: "v", root: "ly", rootMeaning: "解开", analysis: "ana-(完全) + lyz(解开) → 完全解开 → 分析", example: "Let's analyze the data carefully.", exampleCn: "让我们仔细分析数据。" },
  { word: "annual", phonetic: "/ˈænjuəl/", meaning: "每年的；年度的", pos: "adj", root: "ann", rootMeaning: "年", analysis: "ann(年) + -ual(…的) → 每年的", example: "The annual meeting will be held next week.", exampleCn: "年会将于下周举行。" },
  { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", meaning: "预期；期望", pos: "v", root: "cip", rootMeaning: "拿", analysis: "anti-(前) + cip(拿) + -ate → 提前拿到 → 预期", example: "We anticipate a good result.", exampleCn: "我们预期好结果。" },
  { word: "apparent", phonetic: "/əˈpærənt/", meaning: "明显的；表面上的", pos: "adj", root: "par", rootMeaning: "出现", analysis: "ap-(向) + par(出现) + -ent → 出现的 → 明显的", example: "It's apparent that he's not happy.", exampleCn: "很明显他不开心。" },
  { word: "appeal", phonetic: "/əˈpiːl/", meaning: "呼吁；吸引；上诉", pos: "v/n", root: "peal", rootMeaning: "推", analysis: "ap-(向) + peal(推) → 推向 → 呼吁", example: "They appealed for help.", exampleCn: "他们呼吁帮助。" },
  { word: "appetite", phonetic: "/ˈæpɪtaɪt/", meaning: "食欲；胃口", pos: "n", root: "pet", rootMeaning: "寻求", analysis: "ap-(向) + pet(寻求) + -ite → 寻求 → 食欲", example: "I have a good appetite today.", exampleCn: "我今天胃口很好。" },
  { word: "apply", phonetic: "/əˈplaɪ/", meaning: "申请；应用", pos: "v", root: "ply", rootMeaning: "折叠", analysis: "ap-(向) + ply(折叠) → 折向 → 应用", example: "You can apply for a scholarship.", exampleCn: "你可以申请奖学金。" },
  { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", meaning: "感激；欣赏；升值", pos: "v", root: "preci", rootMeaning: "价值", analysis: "ap-(向) + preci(价值) + -ate → 对价值认可 → 感激", example: "I appreciate your help.", exampleCn: "我感谢你的帮助。" },
  { word: "approach", phonetic: "/əˈprəʊtʃ/", meaning: "方法；靠近", pos: "v/n", root: "proach", rootMeaning: "近", analysis: "ap-(向) + proach(近) → 向…靠近 → 方法", example: "We need a new approach to this problem.", exampleCn: "我们需要解决这个问题的新方法。" },
  { word: "appropriate", phonetic: "/əˈprəʊpriət/", meaning: "适当的；合适的", pos: "adj", root: "propri", rootMeaning: "自己的", analysis: "ap-(向) + propri(自己的) + -ate → 成为自己的 → 适当的", example: "Wear appropriate clothes for the interview.", exampleCn: "面试穿合适的衣服。" },
  { word: "approve", phonetic: "/əˈpruːv/", meaning: "批准；赞成", pos: "v", root: "prov", rootMeaning: "证明", analysis: "ap-(向) + prov(证明) → 证明…好 → 批准", example: "The manager approved my request.", exampleCn: "经理批准了我的请求。" },
  { word: "arise", phonetic: "/əˈraɪz/", meaning: "出现；产生", pos: "v", root: "rise", rootMeaning: "升起", analysis: "a-(向) + rise(升起) → 升起来 → 出现", verbForms: { past: "arose", pastParticiple: "arisen", presentParticiple: "arising" }, example: "Problems may arise at any time.", exampleCn: "问题随时可能出现。" },
  { word: "artificial", phonetic: "/ˌɑːtɪˈfɪʃl/", meaning: "人工的；人造的", pos: "adj", root: "art", rootMeaning: "技艺", analysis: "art(技艺) + -ficial(做的) → 人工做的 → 人造的", example: "Artificial intelligence is developing fast.", exampleCn: "人工智能发展迅速。" },
  { word: "assemble", phonetic: "/əˈsembl/", meaning: "组装；集合", pos: "v", root: "sembl", rootMeaning: "相同", analysis: "as-(向) + sembl(相同) → 聚到一起 → 集合", example: "The students assembled in the hall.", exampleCn: "学生们在大厅集合。" },
  { word: "assess", phonetic: "/əˈses/", meaning: "评估；评定", pos: "v", root: "sess", rootMeaning: "坐", analysis: "as-(旁) + sess(坐) → 坐在旁边 → 评估", example: "We need to assess the situation.", exampleCn: "我们需要评估形势。" },
  { word: "assign", phonetic: "/əˈsaɪn/", meaning: "分配；指派", pos: "v", root: "sign", rootMeaning: "标记", analysis: "as-(向) + sign(标记) → 标记给人 → 分配", example: "The teacher assigned homework.", exampleCn: "老师布置了作业。" },
  { word: "assist", phonetic: "/əˈsɪst/", meaning: "帮助；协助", pos: "v", root: "sist", rootMeaning: "站立", analysis: "as-(旁) + sist(站立) → 站在旁边 → 帮助", example: "Can I assist you with anything?", exampleCn: "我能帮你什么吗？" },
  { word: "associate", phonetic: "/əˈsəʊʃieɪt/", meaning: "联系；关联", pos: "v/n", root: "soci", rootMeaning: "同伴", analysis: "as-(向) + soci(同伴) + -ate → 结伴 → 联系", example: "We often associate red with danger.", exampleCn: "我们常把红色与危险联系在一起。" },
  { word: "assume", phonetic: "/əˈsjuːm/", meaning: "假设；承担", pos: "v", root: "sum", rootMeaning: "拿", analysis: "as-(向) + sum(拿) → 拿去 → 承担", example: "I assume you've finished your work.", exampleCn: "我猜你已完成工作了。" },
  { word: "atmosphere", phonetic: "/ˈætməsfɪə/", meaning: "气氛；大气层", pos: "n", root: "sphere", rootMeaning: "球体", analysis: "atmo-(蒸汽) + sphere(球体) → 包围球体的气体 → 大气层", example: "The restaurant has a nice atmosphere.", exampleCn: "这家餐厅气氛很好。" },
  { word: "attach", phonetic: "/əˈtætʃ/", meaning: "附上；连接", pos: "v", root: "tach", rootMeaning: "固定", analysis: "at-(向) + tach(固定) → 固定到 → 附上", example: "Please attach your photo to the form.", exampleCn: "请把照片附在表格上。" },
  { word: "attempt", phonetic: "/əˈtempt/", meaning: "尝试；企图", pos: "v/n", root: "tempt", rootMeaning: "尝试", analysis: "at-(向) + tempt(尝试) → 去尝试 → 企图", example: "He attempted to break the record.", exampleCn: "他试图打破纪录。" },
  { word: "attribute", phonetic: "/əˈtrɪbjuːt/", meaning: "属性；归因于", pos: "n/v", root: "tribut", rootMeaning: "给予", analysis: "at-(向) + tribut(给予) → 把…给予 → 归因于", example: "She attributes her success to hard work.", exampleCn: "她把成功归因于努力。" },
  { word: "available", phonetic: "/əˈveɪləbl/", meaning: "可用的；有空的", pos: "adj", root: "vail", rootMeaning: "价值", analysis: "a-(向) + vail(价值) + -able → 有价值的 → 可用的", example: "Is this seat available?", exampleCn: "这个座位有人吗？" },
  { word: "aware", phonetic: "/əˈweə/", meaning: "意识到的；知道的", pos: "adj", root: "ware", rootMeaning: "注意", analysis: "a-(向) + ware(注意) → 注意到 → 意识到的", example: "Are you aware of the risks?", exampleCn: "你意识到风险了吗？" },
  { word: "barrier", phonetic: "/ˈbæriə/", meaning: "障碍；壁垒", pos: "n", root: "bar", rootMeaning: "横木", analysis: "bar(横木) + -rier → 横在面前的 → 障碍", example: "Language is a barrier to communication.", exampleCn: "语言是交流的障碍。" },
  { word: "benefit", phonetic: "/ˈbenɪfɪt/", meaning: "利益；受益", pos: "n/v", root: "bene-", rootMeaning: "好", analysis: "bene-(好) + fit(做) → 做好事 → 利益", example: "Exercise benefits your health.", exampleCn: "运动有益健康。" },
  { word: "capable", phonetic: "/ˈkeɪpəbl/", meaning: "有能力的", pos: "adj", root: "cap", rootMeaning: "拿", analysis: "cap(拿) + -able(能) → 能拿住的 → 有能力的", example: "She is capable of doing the job.", exampleCn: "她有能力做这份工作。" },
  { word: "circumstance", phonetic: "/ˈsɜːkəmstəns/", meaning: "环境；情况", pos: "n", root: "circum-", rootMeaning: "周围", analysis: "circum-(周围) + stance(站立) → 站在周围 → 环境", example: "Under no circumstances should you lie.", exampleCn: "在任何情况下你都不应撒谎。" },
  { word: "community", phonetic: "/kəˈmjuːnəti/", meaning: "社区；团体", pos: "n", root: "mun", rootMeaning: "公共", analysis: "com-(共同) + mun(公共) + -ity → 公共团体 → 社区", example: "We live in a close-knit community.", exampleCn: "我们住在一个紧密的社区。" },
  { word: "complex", phonetic: "/ˈkɒmpleks/", meaning: "复杂的", pos: "adj", root: "plex", rootMeaning: "折叠", analysis: "com-(共同) + plex(折叠) → 叠在一起的 → 复杂的", example: "The problem is very complex.", exampleCn: "这个问题很复杂。" },
  { word: "concentrate", phonetic: "/ˈkɒnsntreɪt/", meaning: "集中；专注", pos: "v", root: "centr", rootMeaning: "中心", analysis: "con-(共同) + centr(中心) + -ate → 共同到中心 → 集中", example: "I can't concentrate on my work.", exampleCn: "我无法集中精力工作。" },
  { word: "confident", phonetic: "/ˈkɒnfɪdənt/", meaning: "自信的；有信心的", pos: "adj", root: "fid", rootMeaning: "信任", analysis: "con-(完全) + fid(信任) + -ent → 完全信任的 → 自信的", example: "She is confident about the exam.", exampleCn: "她对考试很有信心。" },
  { word: "conflict", phonetic: "/ˈkɒnflɪkt/", meaning: "冲突；矛盾", pos: "n/v", root: "flict", rootMeaning: "打击", analysis: "con-(共同) + flict(打击) → 互打 → 冲突", example: "The two countries are in conflict.", exampleCn: "两国处于冲突之中。" },
  { word: "conscious", phonetic: "/ˈkɒnʃəs/", meaning: "有意识的；清醒的", pos: "adj", root: "sci", rootMeaning: "知道", analysis: "con-(完全) + sci(知道) + -ous → 完全知道的 → 有意识的", example: "She is conscious of her responsibilities.", exampleCn: "她清楚自己的责任。" },
  { word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", meaning: "结果；后果", pos: "n", root: "sequ", rootMeaning: "跟随", analysis: "con-(共同) + sequ(跟随) + -ence → 跟随而来 → 结果", example: "You must face the consequences.", exampleCn: "你必须面对后果。" },
  { word: "consider", phonetic: "/kənˈsɪdə/", meaning: "考虑；认为", pos: "v", root: "sider", rootMeaning: "星", analysis: "con-(完全) + sider(星) → 观星思考 → 考虑", example: "Please consider my suggestion.", exampleCn: "请考虑我的建议。" },
  { word: "consist", phonetic: "/kənˈsɪst/", meaning: "组成；在于", pos: "v", root: "sist", rootMeaning: "站立", analysis: "con-(共同) + sist(站立) → 站在一起 → 组成", example: "The team consists of 5 members.", exampleCn: "团队由5名成员组成。" },
  { word: "constant", phonetic: "/ˈkɒnstənt/", meaning: "持续的；不断的", pos: "adj", root: "stant", rootMeaning: "站立", analysis: "con-(完全) + stant(站立) → 一直站着 → 持续的", example: "The baby needs constant attention.", exampleCn: "婴儿需要不断的关注。" },
  { word: "consume", phonetic: "/kənˈsjuːm/", meaning: "消费；消耗", pos: "v", root: "sum", rootMeaning: "拿", analysis: "con-(完全) + sum(拿) → 完全拿走 → 消耗", example: "We consume a lot of energy every day.", exampleCn: "我们每天消耗大量能源。" },
  { word: "contribute", phonetic: "/kənˈtrɪbjuːt/", meaning: "贡献；捐献", pos: "v", root: "tribut", rootMeaning: "给予", analysis: "con-(完全) + tribut(给予) → 完全给予 → 贡献", example: "Everyone should contribute to society.", exampleCn: "每个人都应该为社会做贡献。" },
  { word: "convenient", phonetic: "/kənˈviːniənt/", meaning: "方便的；便利的", pos: "adj", root: "ven", rootMeaning: "来", analysis: "con-(共同) + ven(来) + -ient → 一起来 → 方便的", example: "Online shopping is very convenient.", exampleCn: "网购非常方便。" },
  { word: "convince", phonetic: "/kənˈvɪns/", meaning: "说服；使信服", pos: "v", root: "vinc", rootMeaning: "征服", analysis: "con-(完全) + vinc(征服) → 完全征服 → 说服", example: "I convinced him to come with us.", exampleCn: "我说服他和我们一起去。" },
  { word: "critical", phonetic: "/ˈkrɪtɪkl/", meaning: "批评的；关键的", pos: "adj", root: "crit", rootMeaning: "判断", analysis: "crit(判断) + -ical(…的) → 判断的 → 批评的", example: "This is a critical moment.", exampleCn: "这是关键时刻。" },
  { word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "下降；拒绝", pos: "v/n", root: "clin", rootMeaning: "倾斜", analysis: "de-(下) + clin(倾斜) → 向下倾斜 → 下降", example: "The number of smokers is declining.", exampleCn: "吸烟者数量在下降。" },
  { word: "defend", phonetic: "/dɪˈfend/", meaning: "防御；为…辩护", pos: "v", root: "fend", rootMeaning: "打击", analysis: "de-(离开) + fend(打击) → 挡开打击 → 防御", example: "We must defend our rights.", exampleCn: "我们必须维护自己的权利。" },
  { word: "define", phonetic: "/dɪˈfaɪn/", meaning: "定义；界定", pos: "v", root: "fin", rootMeaning: "界限", analysis: "de-(完全) + fin(界限) → 划定界限 → 定义", example: "How do you define success?", exampleCn: "你如何定义成功？" },
  { word: "depress", phonetic: "/dɪˈpres/", meaning: "使沮丧；压低", pos: "v", root: "press", rootMeaning: "压", analysis: "de-(下) + press(压) → 向下压 → 使沮丧", example: "The bad news depressed him.", exampleCn: "坏消息让他很沮丧。" },
  { word: "deserve", phonetic: "/dɪˈzɜːv/", meaning: "值得；应得", pos: "v", root: "serv", rootMeaning: "服务", analysis: "de-(完全) + serv(服务) → 全心全意服务 → 值得", example: "You deserve a reward.", exampleCn: "你应该得到奖励。" },
  { word: "desire", phonetic: "/dɪˈzaɪə/", meaning: "渴望；欲望", pos: "v/n", root: "sider", rootMeaning: "星", analysis: "de-(加强) + sir(星) → 向往星辰 → 渴望", example: "She has a strong desire to learn.", exampleCn: "她有强烈的学习愿望。" },
  { word: "desperate", phonetic: "/ˈdespərət/", meaning: "绝望的；不顾一切的", pos: "adj", root: "sper", rootMeaning: "希望", analysis: "de-(否定) + sper(希望) + -ate → 没有希望 → 绝望的", example: "He was desperate for help.", exampleCn: "他急需帮助。" },
  { word: "despite", phonetic: "/dɪˈspaɪt/", meaning: "尽管", pos: "prep", root: "spite", rootMeaning: "看", analysis: "de-(向下) + spite(看) → 看不起 → 尽管", example: "Despite the rain, we went out.", exampleCn: "尽管下雨，我们还是出去了。" },
  { word: "device", phonetic: "/dɪˈvaɪs/", meaning: "设备；装置", pos: "n", root: "vice", rootMeaning: "看", analysis: "de-(分开) + vice(看) → 分开看的东西 → 设备", example: "This device can measure temperature.", exampleCn: "这个设备可以测量温度。" },
  { word: "devote", phonetic: "/dɪˈvəʊt/", meaning: "致力于；奉献", pos: "v", root: "vot", rootMeaning: "发誓", analysis: "de-(完全) + vot(发誓) → 发誓做 → 致力于", example: "He devoted his life to science.", exampleCn: "他把一生献给了科学。" },
  { word: "domestic", phonetic: "/dəˈmestɪk/", meaning: "国内的；家庭的", pos: "adj", root: "dom", rootMeaning: "家", analysis: "dom(家) + -estic(…的) → 家的 → 国内的", example: "Domestic flights are cheaper.", exampleCn: "国内航班更便宜。" },
  { word: "dominant", phonetic: "/ˈdɒmɪnənt/", meaning: "主导的；占优势的", pos: "adj", root: "domin", rootMeaning: "主人", analysis: "domin(主人) + -ant → 主人的 → 主导的", example: "English is the dominant language online.", exampleCn: "英语是网络上的主导语言。" },
  { word: "eliminate", phonetic: "/ɪˈlɪmɪneɪt/", meaning: "消除；淘汰", pos: "v", root: "limin", rootMeaning: "门槛", analysis: "e-(出) + limin(门槛) + -ate → 逐出门外 → 消除", example: "We must eliminate all errors.", exampleCn: "我们必须消除所有错误。" },
  { word: "emerge", phonetic: "/ɪˈmɜːdʒ/", meaning: "出现；浮现", pos: "v", root: "merg", rootMeaning: "沉没", analysis: "e-(出) + merg(沉) → 从沉没中出来 → 出现", example: "New problems keep emerging.", exampleCn: "新问题不断出现。" },
  { word: "emphasize", phonetic: "/ˈemfəsaɪz/", meaning: "强调", pos: "v", root: "pha", rootMeaning: "显示", analysis: "em-(使) + pha(显示) + -size → 使显示 → 强调", example: "The teacher emphasized the importance of reading.", exampleCn: "老师强调了阅读的重要性。" },
  { word: "employ", phonetic: "/ɪmˈplɔɪ/", meaning: "雇佣；使用", pos: "v", root: "ploy", rootMeaning: "折叠", analysis: "em-(使) + ploy(折叠) → 使参与 → 雇佣", example: "The company employs over 200 people.", exampleCn: "这家公司雇佣了200多人。" },
  { word: "encounter", phonetic: "/ɪnˈkaʊntə/", meaning: "遭遇；遇到", pos: "v/n", root: "counter", rootMeaning: "相对的", analysis: "en-(使) + counter(相对) → 相对而来 → 遭遇", example: "We encountered some difficulties.", exampleCn: "我们遇到了一些困难。" },
  { word: "engage", phonetic: "/ɪnˈɡeɪdʒ/", meaning: "从事；订婚；吸引", pos: "v", root: "gage", rootMeaning: "承诺", analysis: "en-(使) + gage(承诺) → 使承诺 → 从事", example: "She engages in volunteer work.", exampleCn: "她从事志愿工作。" },
  { word: "enormous", phonetic: "/ɪˈnɔːməs/", meaning: "巨大的", pos: "adj", root: "norm", rootMeaning: "规范", analysis: "e-(出) + norm(规范) + -ous → 超出常规的 → 巨大的", example: "The project required enormous effort.", exampleCn: "这个项目需要巨大的努力。" },
  { word: "ensure", phonetic: "/ɪnˈʃʊə/", meaning: "确保；保证", pos: "v", root: "sur", rootMeaning: "确定", analysis: "en-(使) + sur(确定) → 使确定 → 确保", example: "Please ensure the door is locked.", exampleCn: "请确保门锁好了。" },
  { word: "enthusiasm", phonetic: "/ɪnˈθjuːziæzəm/", meaning: "热情；热心", pos: "n", root: "theo", rootMeaning: "神", analysis: "en-(在) + thu(theo神) + -siasm → 有神在心中的状态 → 热情", example: "He shows great enthusiasm for music.", exampleCn: "他对音乐表现出极大的热情。" },
  { word: "essential", phonetic: "/ɪˈsenʃl/", meaning: "必要的；本质的", pos: "adj", root: "esse", rootMeaning: "存在", analysis: "ess(存在) + -ential → 存在所必需的 → 必要的", example: "Water is essential for life.", exampleCn: "水对生命是必不可少的。" },
  { word: "establish", phonetic: "/ɪˈstæblɪʃ/", meaning: "建立；确立", pos: "v", root: "stab", rootMeaning: "稳定", analysis: "e-(出) + stabl(稳定) + -ish → 使稳定 → 建立", example: "The company was established in 1990.", exampleCn: "公司成立于1990年。" },
  { word: "estimate", phonetic: "/ˈestɪmeɪt/", meaning: "估计；估算", pos: "v/n", root: "estim", rootMeaning: "价值", analysis: "estim(价值) + -ate → 评估价值 → 估计", example: "We estimate the cost will be around $1000.", exampleCn: "我们估计费用约1000美元。" },
  { word: "evaluate", phonetic: "/ɪˈvæljueɪt/", meaning: "评估；评价", pos: "v", root: "val", rootMeaning: "价值", analysis: "e-(出) + val(价值) + -uate → 给出价值 → 评价", example: "We need to evaluate the results.", exampleCn: "我们需要评估结果。" },
  { word: "eventually", phonetic: "/ɪˈventʃuəli/", meaning: "最终；终于", pos: "adv", root: "vent", rootMeaning: "来", analysis: "e-(出) + vent(来) + -ually → 终将出来 → 最终", example: "Eventually, everything worked out.", exampleCn: "最终一切顺利。" },
  { word: "evidence", phonetic: "/ˈevɪdəns/", meaning: "证据；迹象", pos: "n", root: "vid", rootMeaning: "看", analysis: "e-(出) + vid(看) + -ence → 看得出 → 证据", example: "There's no evidence to support his claim.", exampleCn: "没有证据支持他的说法。" },
  { word: "evolve", phonetic: "/ɪˈvɒlv/", meaning: "进化；发展", pos: "v", root: "volv", rootMeaning: "转", analysis: "e-(出) + volv(转) → 转出来 → 进化", example: "Species evolve over time.", exampleCn: "物种随时间进化。" },
  { word: "expand", phonetic: "/ɪkˈspænd/", meaning: "扩展；扩大", pos: "v", root: "pand", rootMeaning: "伸展", analysis: "ex-(出) + pand(伸展) → 向外伸展 → 扩展", example: "The company plans to expand overseas.", exampleCn: "公司计划向海外扩展。" },
  { word: "exploit", phonetic: "/ɪkˈsplɔɪt/", meaning: "开发；利用；剥削", pos: "v/n", root: "ploit", rootMeaning: "折叠", analysis: "ex-(出) + ploit(折叠) → 展开 → 开发", example: "We should exploit natural resources wisely.", exampleCn: "我们应该明智地开发自然资源。" },
  { word: "external", phonetic: "/ɪkˈstɜːnl/", meaning: "外部的；外表的", pos: "adj", root: "extern", rootMeaning: "外", analysis: "extern(外) + -al(…的) → 外部的", example: "External factors also matter.", exampleCn: "外部因素也很重要。" },
  { word: "extraordinary", phonetic: "/ɪkˈstrɔːdnri/", meaning: "非凡的；特别的", pos: "adj", root: "ordin", rootMeaning: "秩序", analysis: "extra-(超出) + ordin(秩序) + -ary → 超出常规的 → 非凡的", example: "She has extraordinary talent.", exampleCn: "她有非凡的才华。" },
  { word: "extreme", phonetic: "/ɪkˈstriːm/", meaning: "极端的；极度的", pos: "adj", root: "extrem", rootMeaning: "最外", analysis: "extr(外) + -eme(最) → 最外面的 → 极端的", example: "Extreme weather is becoming more common.", exampleCn: "极端天气越来越常见。" },
  { word: "facility", phonetic: "/fəˈsɪləti/", meaning: "设施；便利", pos: "n", root: "fac", rootMeaning: "做", analysis: "fac(做) + -ility(能力) → 能做事的 → 设施", example: "The hotel has excellent facilities.", exampleCn: "这家酒店设施很好。" },
  { word: "faithful", phonetic: "/ˈfeɪθfl/", meaning: "忠诚的；忠实的", pos: "adj", root: "faith", rootMeaning: "信任", analysis: "faith(信任) + -ful(充满) → 充满信任的 → 忠诚的", example: "A faithful friend is priceless.", exampleCn: "忠实的朋友是无价的。" },
  { word: "familiar", phonetic: "/fəˈmɪliə/", meaning: "熟悉的", pos: "adj", root: "famil", rootMeaning: "家庭", analysis: "famil(家庭) + -iar → 像家人一样的 → 熟悉的", example: "This song sounds familiar.", exampleCn: "这首歌听起来很熟悉。" },
  { word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "灵活的；柔韧的", pos: "adj", root: "flex", rootMeaning: "弯曲", analysis: "flex(弯曲) + -ible(能) → 能弯曲的 → 灵活的", example: "We need a flexible schedule.", exampleCn: "我们需要一个灵活的时间表。" },
  { word: "frequent", phonetic: "/ˈfriːkwənt/", meaning: "频繁的；经常的", pos: "adj", root: "frequ", rootMeaning: "频繁", analysis: "frequ(频繁) + -ent(…的) → 频繁的", example: "She makes frequent trips abroad.", exampleCn: "她频繁出国旅行。" },
  { word: "fundamental", phonetic: "/ˌfʌndəˈmentl/", meaning: "基本的；根本的", pos: "adj", root: "fund", rootMeaning: "基础", analysis: "fund(基础) + -amental → 基础的 → 基本的", example: "This is a fundamental principle.", exampleCn: "这是一个基本原则。" },
  { word: "generate", phonetic: "/ˈdʒenəreɪt/", meaning: "产生；生成", pos: "v", root: "gen", rootMeaning: "产生", analysis: "gen(产生) + -erate → 产生", example: "The wind generates electricity.", exampleCn: "风能发电。" },
  { word: "generous", phonetic: "/ˈdʒenərəs/", meaning: "慷慨的；大方的", pos: "adj", root: "gen", rootMeaning: "种类", analysis: "gen(种类) + -erous → 同种类的 → 慷慨的", example: "He is generous with his time.", exampleCn: "他在时间上很大方。" },
  { word: "genuine", phonetic: "/ˈdʒenjuɪn/", meaning: "真正的；真诚的", pos: "adj", root: "gen", rootMeaning: "出生", analysis: "gen(出生) + -uine → 天生的 → 真正的", example: "This is a genuine leather bag.", exampleCn: "这是真皮包。" },
  { word: "guarantee", phonetic: "/ˌɡærənˈtiː/", meaning: "保证；担保", pos: "v/n", root: "guarant", rootMeaning: "保证", analysis: "guarant(保证) + -ee → 保证", example: "We guarantee the quality of our products.", exampleCn: "我们保证产品质量。" },
  { word: "hesitate", phonetic: "/ˈhezɪteɪt/", meaning: "犹豫", pos: "v", root: "hes", rootMeaning: "粘着", analysis: "hes(粘着) + -itate → 粘住 → 犹豫", example: "Don't hesitate to ask questions.", exampleCn: "有问题尽管问。" },
  { word: "identity", phonetic: "/aɪˈdentəti/", meaning: "身份；同一性", pos: "n", root: "idem", rootMeaning: "相同", analysis: "ident(相同) + -ity → 相同性 → 身份", example: "Please show your identity card.", exampleCn: "请出示你的身份证。" },
  { word: "illustrate", phonetic: "/ˈɪləstreɪt/", meaning: "说明；举例说明", pos: "v", root: "lustr", rootMeaning: "照亮", analysis: "il-(使) + lustr(照亮) + -ate → 使明亮 → 说明", example: "Let me illustrate my point with a story.", exampleCn: "让我用一个故事来说明我的观点。" },
  { word: "immediate", phonetic: "/ɪˈmiːdiət/", meaning: "立即的；直接的", pos: "adj", root: "medi", rootMeaning: "中间", analysis: "im-(无) + medi(中间) + -ate → 无中间环节的 → 立即的", example: "We need an immediate solution.", exampleCn: "我们需要立即的解决方案。" },
  { word: "impact", phonetic: "/ˈɪmpækt/", meaning: "影响；冲击", pos: "n/v", root: "pact", rootMeaning: "打击", analysis: "im-(向内) + pact(打击) → 向内打击 → 影响", example: "The Internet has a huge impact on our lives.", exampleCn: "互联网对我们生活有巨大影响。" },
  { word: "implement", phonetic: "/ˈɪmplɪment/", meaning: "实施；执行", pos: "v", root: "ple", rootMeaning: "填满", analysis: "im-(使) + ple(填满) + -ment → 使完善 → 实施", example: "How do we implement this plan?", exampleCn: "我们如何实施这个计划？" },
  { word: "imply", phonetic: "/ɪmˈplaɪ/", meaning: "暗示；意味着", pos: "v", root: "ply", rootMeaning: "折叠", analysis: "im-(内) + ply(折叠) → 折在里面 → 暗示", example: "What are you implying?", exampleCn: "你在暗示什么？" },
  { word: "independent", phonetic: "/ˌɪndɪˈpendənt/", meaning: "独立的", pos: "adj", root: "pend", rootMeaning: "悬挂", analysis: "in-(不) + de-(下) + pend(悬挂) + -ent → 不悬挂于他人 → 独立的", example: "She is an independent woman.", exampleCn: "她是个独立的女性。" },
  { word: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/", meaning: "个人的；个体", pos: "n/adj", root: "divid", rootMeaning: "分割", analysis: "in-(不) + divid(分割) + -ual → 不可分割的 → 个体", example: "Each individual is unique.", exampleCn: "每个人都是独特的。" },
  { word: "inferior", phonetic: "/ɪnˈfɪəriə/", meaning: "劣等的；下级的", pos: "adj", root: "fer", rootMeaning: "带", analysis: "infer-(下面) + -ior → 下面的人 → 下级的", example: "This product is inferior in quality.", exampleCn: "这个产品质量较差。" },
  { word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "影响；影响力", pos: "n/v", root: "flu", rootMeaning: "流", analysis: "in-(入) + flu(流) + -ence → 流入 → 影响", example: "His words influenced my decision.", exampleCn: "他的话影响了我的决定。" },
  { word: "initial", phonetic: "/ɪˈnɪʃl/", meaning: "最初的；初始的", pos: "adj", root: "init", rootMeaning: "开始", analysis: "in-(入) + it(走) + -ial → 走进去 → 最初的", example: "My initial reaction was surprise.", exampleCn: "我最初的反应是惊讶。" },
  { word: "innocent", phonetic: "/ˈɪnəsnt/", meaning: "无辜的；天真的", pos: "adj", root: "noc", rootMeaning: "伤害", analysis: "in-(不) + noc(伤害) + -ent → 不伤害人的 → 无辜的", example: "He is innocent of the crime.", exampleCn: "他是无罪的。" },
  { word: "insist", phonetic: "/ɪnˈsɪst/", meaning: "坚持；坚决要求", pos: "v", root: "sist", rootMeaning: "站立", analysis: "in-(上) + sist(站立) → 站在上面 → 坚持", example: "She insists on paying for dinner.", exampleCn: "她坚持要付晚餐钱。" },
  { word: "inspire", phonetic: "/ɪnˈspaɪə/", meaning: "激励；启发", pos: "v", root: "spir", rootMeaning: "呼吸", analysis: "in-(入) + spir(呼吸) → 吹入气息 → 激励", example: "His story inspired many people.", exampleCn: "他的故事激励了很多人。" },
  { word: "instance", phonetic: "/ˈɪnstəns/", meaning: "例子；实例", pos: "n", root: "stance", rootMeaning: "站立", analysis: "in-(上) + stance(站立) → 站在上面 → 例子", example: "For instance, you can try this method.", exampleCn: "例如，你可以试试这个方法。" },
  { word: "intense", phonetic: "/ɪnˈtens/", meaning: "强烈的；紧张的", pos: "adj", root: "tens", rootMeaning: "伸展", analysis: "in-(向内) + tens(伸展) → 向内伸展 → 强烈的", example: "The heat was intense.", exampleCn: "热度很强烈。" },
  { word: "involve", phonetic: "/ɪnˈvɒlv/", meaning: "涉及；包含；参与", pos: "v", root: "volv", rootMeaning: "转", analysis: "in-(入) + volv(转) → 卷入 → 涉及", example: "The job involves a lot of travel.", exampleCn: "这份工作需要大量出差。" },
  { word: "issue", phonetic: "/ˈɪʃuː/", meaning: "问题；议题；发布", pos: "n/v", root: "iss", rootMeaning: "走", analysis: "is(走) + -sue → 走出去 → 发布", example: "Climate change is a serious issue.", exampleCn: "气候变化是严重的问题。" },
  { word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", meaning: "证明…正当；为…辩护", pos: "v", root: "just", rootMeaning: "公正", analysis: "just(公正) + -ify(使) → 使公正 → 证明正当", example: "How can you justify your behavior?", exampleCn: "你如何为你的行为辩护？" },
  { word: "likely", phonetic: "/ˈlaɪkli/", meaning: "可能的；很可能", pos: "adj/adv", root: "like", rootMeaning: "相似", analysis: "like(相似) + -ly → 像是 → 可能的", example: "It's likely to rain tomorrow.", exampleCn: "明天可能会下雨。" },
  { word: "locate", phonetic: "/ləʊˈkeɪt/", meaning: "找到；位于", pos: "v", root: "loc", rootMeaning: "地方", analysis: "loc(地方) + -ate → 放在某个地方 → 位于", example: "The hotel is located near the beach.", exampleCn: "酒店位于海滩附近。" },
  { word: "mental", phonetic: "/ˈmentl/", meaning: "心理的；精神的", pos: "adj", root: "ment", rootMeaning: "心智", analysis: "ment(心智) + -al(…的) → 心智的 → 心理的", example: "Mental health is as important as physical health.", exampleCn: "心理健康和身体健康一样重要。" },
  { word: "minor", phonetic: "/ˈmaɪnə/", meaning: "次要的；较小的", pos: "adj", root: "min", rootMeaning: "小", analysis: "min(小) + -or → 较小的", example: "There are only a few minor problems.", exampleCn: "只有一些小问题。" },
  { word: "negative", phonetic: "/ˈneɡətɪv/", meaning: "消极的；负面的", pos: "adj", root: "neg", rootMeaning: "否定", analysis: "neg(否定) + -ative → 否定的 → 消极的", example: "Don't have a negative attitude.", exampleCn: "不要有消极态度。" },
  { word: "negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "谈判；协商", pos: "v", root: "neg", rootMeaning: "否定", analysis: "neg(不) + oti(闲暇) + -ate → 没有闲暇 → 谈判", example: "They are negotiating a peace deal.", exampleCn: "他们正在谈判和平协议。" },
  { word: "normal", phonetic: "/ˈnɔːml/", meaning: "正常的；标准的", pos: "adj", root: "norm", rootMeaning: "规范", analysis: "norm(规范) + -al(…的) → 符合规范的 → 正常的", example: "It's normal to feel nervous.", exampleCn: "感到紧张是正常的。" },
  { word: "numerous", phonetic: "/ˈnjuːmərəs/", meaning: "许多的；众多的", pos: "adj", root: "numer", rootMeaning: "数字", analysis: "numer(数字) + -ous → 数量多的 → 众多的", example: "Numerous people attended the concert.", exampleCn: "许多人参加了音乐会。" },
  { word: "observe", phonetic: "/əbˈzɜːv/", meaning: "观察；遵守", pos: "v", root: "serv", rootMeaning: "保存", analysis: "ob-(向) + serv(保存) → 保存/观察 → 遵守", example: "We must observe the rules.", exampleCn: "我们必须遵守规则。" },
  { word: "obvious", phonetic: "/ˈɒbviəs/", meaning: "明显的", pos: "adj", root: "vi", rootMeaning: "路", analysis: "ob-(前) + vi(路) + -ous → 摆在路前的 → 明显的", example: "The answer is obvious.", exampleCn: "答案很明显。" },
  { word: "occupy", phonetic: "/ˈɒkjupaɪ/", meaning: "占据；使忙碌", pos: "v", root: "cup", rootMeaning: "拿", analysis: "oc-(向) + cup(拿) + -y → 拿去 → 占据", example: "Reading occupies most of my free time.", exampleCn: "阅读占据了我大部分空闲时间。" },
  { word: "offend", phonetic: "/əˈfend/", meaning: "冒犯；得罪", pos: "v", root: "fend", rootMeaning: "打击", analysis: "of-(反) + fend(打击) → 反击 → 冒犯", example: "I didn't mean to offend you.", exampleCn: "我不是故意冒犯你的。" },
  { word: "operate", phonetic: "/ˈɒpəreɪt/", meaning: "操作；运转；手术", pos: "v", root: "oper", rootMeaning: "工作", analysis: "oper(工作) + -ate → 工作 → 操作", example: "Do you know how to operate this machine?", exampleCn: "你知道怎么操作这台机器吗？" },
  { word: "organize", phonetic: "/ˈɔːɡənaɪz/", meaning: "组织；安排", pos: "v", root: "organ", rootMeaning: "器官/工具", analysis: "organ(器官) + -ize → 使有机能 → 组织", example: "We need to organize our time better.", exampleCn: "我们需要更好地安排时间。" },
  { word: "original", phonetic: "/əˈrɪdʒənl/", meaning: "原始的；独创的", pos: "adj", root: "orig", rootMeaning: "起源", analysis: "orig(起源) + -inal → 起源的 → 原始的", example: "This is an original idea.", exampleCn: "这是一个原创的想法。" },
  { word: "participate", phonetic: "/pɑːˈtɪsɪpeɪt/", meaning: "参与；参加", pos: "v", root: "cip", rootMeaning: "拿", analysis: "part(部分) + i + cip(拿) + -ate → 拿一部分 → 参与", example: "Everyone is encouraged to participate.", exampleCn: "鼓励每个人都参与。" },
  { word: "particular", phonetic: "/pəˈtɪkjələ/", meaning: "特别的；特定的", pos: "adj", root: "part", rootMeaning: "部分", analysis: "part(部分) + -icular → 一小部分 → 特别的", example: "I have a particular interest in history.", exampleCn: "我对历史有特别的兴趣。" },
  { word: "patient", phonetic: "/ˈpeɪʃnt/", meaning: "有耐心的；病人", pos: "adj/n", root: "pati", rootMeaning: "忍受", analysis: "pati(忍受) + -ent → 忍受的 → 有耐心的", example: "You need to be patient with children.", exampleCn: "你需要对孩子有耐心。" },
  { word: "peculiar", phonetic: "/pɪˈkjuːliə/", meaning: "奇怪的；独特的", pos: "adj", root: "pecu", rootMeaning: "私人", analysis: "pecu(私人) + -liar → 私人的 → 独特的", example: "There's a peculiar smell in the room.", exampleCn: "房间里有一股奇怪的味道。" },
  { word: "permanent", phonetic: "/ˈpɜːmənənt/", meaning: "永久的；长期的", pos: "adj", root: "man", rootMeaning: "停留", analysis: "per-(贯穿) + man(停留) + -ent → 一直停留 → 永久的", example: "This is not a permanent solution.", exampleCn: "这不是永久的解决方案。" },
  { word: "possess", phonetic: "/pəˈzes/", meaning: "拥有；具有", pos: "v", root: "sess", rootMeaning: "坐", analysis: "pos-(能) + sess(坐) → 能坐在上面 → 拥有", example: "She possesses great talent.", exampleCn: "她拥有巨大的才能。" },
  { word: "potential", phonetic: "/pəˈtenʃl/", meaning: "潜力；潜在的", pos: "n/adj", root: "poten", rootMeaning: "能力", analysis: "poten(能力) + -tial → 有能力的 → 潜力", example: "You have great potential.", exampleCn: "你潜力巨大。" },
  { word: "precious", phonetic: "/ˈpreʃəs/", meaning: "珍贵的；宝贵的", pos: "adj", root: "preci", rootMeaning: "价值", analysis: "preci(价值) + -ous → 有价值的 → 珍贵的", example: "Time is precious.", exampleCn: "时间很宝贵。" },
  { word: "prefer", phonetic: "/prɪˈfɜː/", meaning: "偏爱；更喜欢", pos: "v", root: "fer", rootMeaning: "携带", analysis: "pre-(先) + fer(携带) → 先拿 → 偏爱", example: "I prefer tea to coffee.", exampleCn: "比起咖啡我更喜欢茶。" },
  { word: "present", phonetic: "/ˈpreznt/", meaning: "现在的；出席的；礼物；呈现", pos: "adj/n/v", root: "sent", rootMeaning: "存在", analysis: "pre-(前) + s(存在) + -ent → 在面前 → 出席的", example: "She presented her findings to the class.", exampleCn: "她向全班展示了她的发现。" },
  { word: "pretend", phonetic: "/prɪˈtend/", meaning: "假装", pos: "v", root: "tend", rootMeaning: "伸展", analysis: "pre-(前) + tend(伸展) → 向前伸展 → 假装", example: "He pretended to be asleep.", exampleCn: "他假装睡着了。" },
  { word: "principle", phonetic: "/ˈprɪnsəpl/", meaning: "原则；原理", pos: "n", root: "prin", rootMeaning: "第一", analysis: "prin(第一) + cip(拿) + -le → 首先要拿住的 → 原则", example: "Stick to your principles.", exampleCn: "坚持你的原则。" },
  { word: "priority", phonetic: "/praɪˈɒrəti/", meaning: "优先；重点", pos: "n", root: "prior", rootMeaning: "前", analysis: "prior(在前的) + -ity → 在前面 → 优先", example: "Safety is our top priority.", exampleCn: "安全是我们的首要任务。" },
  { word: "professional", phonetic: "/prəˈfeʃənl/", meaning: "专业的；职业的", pos: "adj/n", root: "fess", rootMeaning: "说", analysis: "pro-(前) + fess(说) + -ional → 在前面说的 → 专业的", example: "She is a professional dancer.", exampleCn: "她是一名专业舞者。" },
  { word: "prohibit", phonetic: "/prəˈhɪbɪt/", meaning: "禁止", pos: "v", root: "hib", rootMeaning: "持有", analysis: "pro-(前) + hibit(持有) → 在前面控制 → 禁止", example: "Smoking is prohibited here.", exampleCn: "此处禁止吸烟。" },
  { word: "property", phonetic: "/ˈprɒpəti/", meaning: "财产；特性；房产", pos: "n", root: "proper", rootMeaning: "自己的", analysis: "proper(自己的) + -ty → 自己的东西 → 财产", example: "Protect your personal property.", exampleCn: "保护好你的个人财产。" },
  { word: "publish", phonetic: "/ˈpʌblɪʃ/", meaning: "出版；发表", pos: "v", root: "publ", rootMeaning: "公众", analysis: "publ(公众) + -ish → 公之于众 → 出版", example: "The book was published last year.", exampleCn: "这本书去年出版了。" },
  { word: "pursue", phonetic: "/pəˈsjuː/", meaning: "追求；追赶", pos: "v", root: "sue", rootMeaning: "跟随", analysis: "pur-(向前) + sue(跟随) → 向前跟随 → 追求", example: "Pursue your dreams bravely.", exampleCn: "勇敢地追求你的梦想。" },
  { word: "quality", phonetic: "/ˈkwɒləti/", meaning: "质量；品质", pos: "n", root: "qual", rootMeaning: "何种", analysis: "qual(何种) + -ity → 什么样子 → 品质", example: "Quality matters more than quantity.", exampleCn: "质量比数量更重要。" },
  { word: "reality", phonetic: "/riˈæləti/", meaning: "现实；事实", pos: "n", root: "real", rootMeaning: "真实", analysis: "real(真实的) + -ity → 真实 → 现实", example: "Face reality bravely.", exampleCn: "勇敢面对现实。" },
  { word: "recommend", phonetic: "/ˌrekəˈmend/", meaning: "推荐；建议", pos: "v", root: "mend", rootMeaning: "委托", analysis: "re-(再) + com(共同) + mend(委托) → 再次委托 → 推荐", example: "I recommend this restaurant.", exampleCn: "我推荐这家餐厅。" },
  { word: "recover", phonetic: "/rɪˈkʌvə/", meaning: "恢复；康复", pos: "v", root: "cover", rootMeaning: "覆盖", analysis: "re-(再) + cover(覆盖) → 重新覆盖 → 恢复", example: "It took her months to recover.", exampleCn: "她花了几个月才恢复。" },
  { word: "refer", phonetic: "/rɪˈfɜː/", meaning: "参考；提及；指的是", pos: "v", root: "fer", rootMeaning: "携带", analysis: "re-(再) + fer(携带) → 再次携带 → 参考", example: "Please refer to the manual.", exampleCn: "请参考手册。" },
  { word: "reflect", phonetic: "/rɪˈflekt/", meaning: "反映；反射；反思", pos: "v", root: "flect", rootMeaning: "弯曲", analysis: "re-(回) + flect(弯曲) → 弯回来 → 反射", example: "The mirror reflects light.", exampleCn: "镜子反射光线。" },
  { word: "regard", phonetic: "/rɪˈɡɑːd/", meaning: "认为；看待；尊重", pos: "v/n", root: "gard", rootMeaning: "看", analysis: "re-(再) + gard(看) → 再看 → 看待", example: "I regard him as a good friend.", exampleCn: "我把他当作好朋友。" },
  { word: "register", phonetic: "/ˈredʒɪstə/", meaning: "注册；登记", pos: "v/n", root: "gister", rootMeaning: "带", analysis: "re-(回) + gister(带) → 带回来 → 登记", example: "You need to register an account.", exampleCn: "你需要注册一个账号。" },
  { word: "regulate", phonetic: "/ˈreɡjuleɪt/", meaning: "调节；管理", pos: "v", root: "reg", rootMeaning: "规则", analysis: "reg(规则) + -ulate → 按规则管理 → 调节", example: "The government regulates food safety.", exampleCn: "政府监管食品安全。" },
  { word: "relate", phonetic: "/rɪˈleɪt/", meaning: "关联；涉及", pos: "v", root: "late", rootMeaning: "携带", analysis: "re-(回) + late(携带) → 带回来 → 关联", example: "How does this relate to our topic?", exampleCn: "这跟我们的主题有什么关联？" },
  { word: "release", phonetic: "/rɪˈliːs/", meaning: "释放；发布；松开", pos: "v/n", root: "lease", rootMeaning: "松", analysis: "re-(回) + lease(松) → 松开 → 释放", example: "The new album was released yesterday.", exampleCn: "新专辑昨天发布了。" },
  { word: "reliable", phonetic: "/rɪˈlaɪəbl/", meaning: "可靠的", pos: "adj", root: "li", rootMeaning: "绑", analysis: "re-(加强) + li(绑) + -able → 可紧紧绑住的 → 可靠的", example: "He is a reliable person.", exampleCn: "他是一个可靠的人。" },
  { word: "religion", phonetic: "/rɪˈlɪdʒən/", meaning: "宗教", pos: "n", root: "lig", rootMeaning: "绑", analysis: "re-(再) + lig(绑) + -ion → 反复绑住 → 宗教", example: "Freedom of religion is important.", exampleCn: "宗教自由很重要。" },
  { word: "rely", phonetic: "/rɪˈlaɪ/", meaning: "依赖；依靠", pos: "v", root: "ly", rootMeaning: "绑", analysis: "re-(加强) + ly(绑) → 紧紧绑住 → 依赖", example: "You can rely on me.", exampleCn: "你可以依靠我。" },
  { word: "remain", phonetic: "/rɪˈmeɪn/", meaning: "保持；剩余", pos: "v", root: "main", rootMeaning: "停留", analysis: "re-(回) + main(停留) → 再停留 → 保持", example: "Please remain seated.", exampleCn: "请保持就坐。" },
  { word: "replace", phonetic: "/rɪˈpleɪs/", meaning: "替代；替换", pos: "v", root: "place", rootMeaning: "放置", analysis: "re-(再) + place(放置) → 重新放置 → 替换", example: "Nothing can replace a mother's love.", exampleCn: "没有什么能替代母爱。" },
  { word: "represent", phonetic: "/ˌreprɪˈzent/", meaning: "代表；表示", pos: "v", root: "sent", rootMeaning: "存在", analysis: "re-(再) + pre-(前) + sent(存在) → 出现在前面 → 代表", example: "She represents our company.", exampleCn: "她代表我们公司。" },
  { word: "request", phonetic: "/rɪˈkwest/", meaning: "请求；要求", pos: "v/n", root: "quest", rootMeaning: "寻求", analysis: "re-(再) + quest(寻求) → 再次寻求 → 请求", example: "May I request a favor?", exampleCn: "我能请你帮个忙吗？" },
  { word: "require", phonetic: "/rɪˈkwaɪə/", meaning: "需要；要求", pos: "v", root: "quir", rootMeaning: "寻求", analysis: "re-(再) + quir(寻求) → 一再寻求 → 需要", example: "The job requires patience.", exampleCn: "这份工作需要耐心。" },
  { word: "reserve", phonetic: "/rɪˈzɜːv/", meaning: "保留；预订", pos: "v/n", root: "serv", rootMeaning: "保存", analysis: "re-(再) + serv(保存) → 再次保存 → 保留", example: "I'd like to reserve a table.", exampleCn: "我想预订一张桌子。" },
  { word: "resist", phonetic: "/rɪˈzɪst/", meaning: "抵抗；抵制", pos: "v", root: "sist", rootMeaning: "站立", analysis: "re-(反) + sist(站立) → 站到对面 → 抵抗", example: "I can't resist chocolate.", exampleCn: "我无法抗拒巧克力。" },
  { word: "resolve", phonetic: "/rɪˈzɒlv/", meaning: "解决；决心", pos: "v", root: "solv", rootMeaning: "解开", analysis: "re-(再) + solv(解开) → 再次解开 → 解决", example: "We need to resolve this conflict.", exampleCn: "我们需要解决这个冲突。" },
  { word: "resource", phonetic: "/rɪˈzɔːs/", meaning: "资源", pos: "n", root: "sourc", rootMeaning: "升起", analysis: "re-(再) + source(来源) → 再来的来源 → 资源", example: "Natural resources are limited.", exampleCn: "自然资源是有限的。" },
  { word: "respond", phonetic: "/rɪˈspɒnd/", meaning: "回应；回答", pos: "v", root: "spond", rootMeaning: "承诺", analysis: "re-(回) + spond(承诺) → 回以承诺 → 回应", example: "Please respond to my email.", exampleCn: "请回复我的邮件。" },
  { word: "responsible", phonetic: "/rɪˈspɒnsəbl/", meaning: "负责的", pos: "adj", root: "spons", rootMeaning: "承诺", analysis: "re-(回) + spons(承诺) + -ible → 能回应承诺的 → 负责的", example: "Who is responsible for this?", exampleCn: "谁对此负责？" },
  { word: "reveal", phonetic: "/rɪˈviːl/", meaning: "揭示；透露", pos: "v", root: "veal", rootMeaning: "面纱", analysis: "re-(去) + veal(面纱) → 去掉面纱 → 揭示", example: "The truth was finally revealed.", exampleCn: "真相终于被揭开了。" },
  { word: "revenue", phonetic: "/ˈrevənjuː/", meaning: "收入；税收", pos: "n", root: "ven", rootMeaning: "来", analysis: "re-(回) + ven(来) + -ue → 回来的钱 → 收入", example: "The company's revenue increased by 20%.", exampleCn: "公司收入增长了20%。" },
  { word: "schedule", phonetic: "/ˈʃedjuːl/", meaning: "时间表；安排", pos: "n/v", root: "sched", rootMeaning: "纸片", analysis: "sched(纸片) + -ule → 小纸片 → 时间表", example: "What's on your schedule today?", exampleCn: "你今天有什么安排？" },
  { word: "secure", phonetic: "/sɪˈkjʊə/", meaning: "安全的；获得", pos: "adj/v", root: "cur", rootMeaning: "关心", analysis: "se-(无) + cur(关心) → 不用担心的 → 安全的", example: "Is your password secure?", exampleCn: "你的密码安全吗？" },
  { word: "senior", phonetic: "/ˈsiːniə/", meaning: "高级的；年长的", pos: "adj/n", root: "sen", rootMeaning: "老", analysis: "sen(老) + -ior → 更老的 → 年长的", example: "He is a senior manager.", exampleCn: "他是一位高级经理。" },
  { word: "sensitive", phonetic: "/ˈsensətɪv/", meaning: "敏感的；灵敏的", pos: "adj", root: "sens", rootMeaning: "感觉", analysis: "sens(感觉) + -itive → 能感觉的 → 敏感的", example: "She is sensitive to criticism.", exampleCn: "她对批评很敏感。" },
  { word: "separate", phonetic: "/ˈsepəreɪt/", meaning: "分开；分离", pos: "v/adj", root: "par", rootMeaning: "准备", analysis: "se-(分开) + par(准备) + -ate → 分开准备 → 分离", example: "Separate the white clothes from the colored ones.", exampleCn: "把白色衣物和有色衣物分开。" },
  { word: "significant", phonetic: "/sɪɡˈnɪfɪkənt/", meaning: "重要的；显著的", pos: "adj", root: "sign", rootMeaning: "标记", analysis: "sign(标记) + -ificant → 值得标记的 → 重要的", example: "This is a significant achievement.", exampleCn: "这是一个重要的成就。" },
  { word: "similar", phonetic: "/ˈsɪmələ/", meaning: "相似的", pos: "adj", root: "simil", rootMeaning: "相似的", analysis: "simil(相似) + -ar → 相似的", example: "Your idea is similar to mine.", exampleCn: "你的想法和我的相似。" },
  { word: "solution", phonetic: "/səˈluːʃn/", meaning: "解决方案", pos: "n", root: "solut", rootMeaning: "解开", analysis: "solut(解开) + -ion → 解开的方法 → 解决方案", example: "Let's find a solution together.", exampleCn: "让我们一起找到解决方案。" },
  { word: "specific", phonetic: "/spəˈsɪfɪk/", meaning: "具体的；特定的", pos: "adj", root: "spec", rootMeaning: "看", analysis: "spec(看) + -ific → 看得清的 → 具体的", example: "Can you be more specific?", exampleCn: "你能说得更具体些吗？" },
  { word: "standard", phonetic: "/ˈstændəd/", meaning: "标准；水平", pos: "n/adj", root: "stand", rootMeaning: "站立", analysis: "stand(站立) + -ard → 站立不倒 → 标准", example: "We have high standards of quality.", exampleCn: "我们有很高的质量标准。" },
  { word: "strategy", phonetic: "/ˈstrætədʒi/", meaning: "策略；战略", pos: "n", root: "strat", rootMeaning: "军队", analysis: "strat(军队) + -egy → 指挥军队的艺术 → 策略", example: "We need a new marketing strategy.", exampleCn: "我们需要新的营销策略。" },
  { word: "struggle", phonetic: "/ˈstrʌɡl/", meaning: "斗争；挣扎；奋斗", pos: "v/n", root: "strugg", rootMeaning: "推", analysis: "strugg(推) + -le → 奋力推 → 奋斗", example: "She struggled to make ends meet.", exampleCn: "她艰难度日。" },
  { word: "sufficient", phonetic: "/səˈfɪʃnt/", meaning: "足够的；充分的", pos: "adj", root: "fic", rootMeaning: "做", analysis: "suf-(下) + fici(做) + -ent → 做够的 → 足够的", example: "We have sufficient food for the trip.", exampleCn: "我们有足够的食物供旅途使用。" },
  { word: "summary", phonetic: "/ˈsʌməri/", meaning: "总结；摘要", pos: "n", root: "sum", rootMeaning: "总和", analysis: "summ(总和) + -ary → 总和的 → 总结", example: "Give me a brief summary.", exampleCn: "给我一个简短的总结。" },
  { word: "superior", phonetic: "/suːˈpɪəriə/", meaning: "优越的；上级的", pos: "adj/n", root: "super", rootMeaning: "上", analysis: "super(上) + -ior → 更高的人 → 上级的", example: "This brand is superior in quality.", exampleCn: "这个品牌质量更优。" },
  { word: "survive", phonetic: "/səˈvaɪv/", meaning: "幸存；生存", pos: "v", root: "viv", rootMeaning: "活", analysis: "sur-(超过) + viv(活) → 活得超过 → 幸存", example: "Only a few people survived the accident.", exampleCn: "只有少数人在事故中幸存。" },
  { word: "suspend", phonetic: "/səˈspend/", meaning: "暂停；悬挂", pos: "v", root: "pend", rootMeaning: "悬挂", analysis: "sus-(下) + pend(悬挂) → 挂在下面 → 暂停", example: "The game was suspended due to rain.", exampleCn: "比赛因雨暂停。" },
  { word: "symbol", phonetic: "/ˈsɪmbl/", meaning: "符号；象征", pos: "n", root: "bol", rootMeaning: "投", analysis: "sym-(共同) + bol(投) → 投到一起 → 象征", example: "The dove is a symbol of peace.", exampleCn: "鸽子是和平的象征。" },
  { word: "temporary", phonetic: "/ˈtemprəri/", meaning: "临时的；暂时的", pos: "adj", root: "tempor", rootMeaning: "时间", analysis: "tempor(时间) + -ary → 短时间的 → 临时的", example: "This is just a temporary arrangement.", exampleCn: "这只是临时的安排。" },
  { word: "tendency", phonetic: "/ˈtendənsi/", meaning: "趋势；倾向", pos: "n", root: "tend", rootMeaning: "伸展", analysis: "tend(伸展) + -ency → 伸向 → 趋势", example: "There's a tendency to work from home.", exampleCn: "有在家工作的趋势。" },
  { word: "tolerate", phonetic: "/ˈtɒləreɪt/", meaning: "容忍；忍受", pos: "v", root: "toler", rootMeaning: "承受", analysis: "toler(承受) + -ate → 承受 → 容忍", example: "I can't tolerate this noise anymore.", exampleCn: "我无法再忍受这种噪音了。" },
  { word: "tradition", phonetic: "/trəˈdɪʃn/", meaning: "传统", pos: "n", root: "trad", rootMeaning: "传递", analysis: "tra-(跨越) + dit(给予) + -ion → 跨越传递 → 传统", example: "This is a family tradition.", exampleCn: "这是家族传统。" },
  { word: "typical", phonetic: "/ˈtɪpɪkl/", meaning: "典型的", pos: "adj", root: "typ", rootMeaning: "类型", analysis: "typ(类型) + -ical → 类型的 → 典型的", example: "This is a typical example.", exampleCn: "这是一个典型的例子。" },
  { word: "ultimate", phonetic: "/ˈʌltɪmət/", meaning: "最终的；终极的", pos: "adj", root: "ultim", rootMeaning: "最后", analysis: "ultim(最后) + -ate → 最后的 → 最终的", example: "The ultimate goal is to be happy.", exampleCn: "最终目标是幸福。" },
  { word: "unique", phonetic: "/juˈniːk/", meaning: "独特的；独一无二的", pos: "adj", root: "un", rootMeaning: "一", analysis: "uni-(一) + -que → 唯一的 → 独特的", example: "Everyone has a unique personality.", exampleCn: "每个人都有独特的个性。" },
  { word: "urgent", phonetic: "/ˈɜːdʒənt/", meaning: "紧急的；迫切的", pos: "adj", root: "urg", rootMeaning: "推动", analysis: "urg(推动) + -ent → 推着要做的 → 紧急的", example: "There's an urgent need for change.", exampleCn: "迫切需要改变。" },
  { word: "utilize", phonetic: "/ˈjuːtəlaɪz/", meaning: "利用；使用", pos: "v", root: "util", rootMeaning: "用", analysis: "util(用) + -ize → 利用", example: "We should utilize our time well.", exampleCn: "我们应该好好利用时间。" },
  { word: "valid", phonetic: "/ˈvælɪd/", meaning: "有效的；合理的", pos: "adj", root: "val", rootMeaning: "价值", analysis: "val(价值) + -id → 有价值的 → 有效的", example: "Your ticket is valid for three days.", exampleCn: "你的票有效期为三天。" },
  { word: "various", phonetic: "/ˈveəriəs/", meaning: "各种各样的", pos: "adj", root: "vari", rootMeaning: "变化", analysis: "vari(变化) + -ous → 变化多的 → 各种各样的", example: "There are various ways to solve this.", exampleCn: "有各种方法可以解决这个问题。" },
  { word: "volume", phonetic: "/ˈvɒljuːm/", meaning: "音量；体积；卷", pos: "n", root: "volv", rootMeaning: "转", analysis: "volv(转) + -ume → 卷起来 → 卷", example: "Please turn down the volume.", exampleCn: "请把音量调低。" },
  { word: "volunteer", phonetic: "/ˌvɒlənˈtɪə/", meaning: "志愿者；自愿", pos: "n/v", root: "vol", rootMeaning: "意愿", analysis: "vol(意愿) + -unteer → 凭意愿做的人 → 志愿者", example: "She volunteers at a local hospital.", exampleCn: "她在当地医院做志愿者。" },
  { word: "witness", phonetic: "/ˈwɪtnəs/", meaning: "目击者；证人", pos: "n/v", root: "wit", rootMeaning: "知道", analysis: "wit(知道) + -ness → 知道事实的人 → 证人", example: "There were no witnesses to the accident.", exampleCn: "事故没有目击者。" },
  { word: "worthwhile", phonetic: "/ˌwɜːθˈwaɪl/", meaning: "值得的", pos: "adj", root: "worth", rootMeaning: "价值", analysis: "worth(价值) + while(时间) → 值时间的 → 值得的", example: "It's a worthwhile investment.", exampleCn: "这是一项值得的投资。" }
];
